CREATE TABLE [dbo].[ADSCPASSW] (
    [ADPS_LOGIN]             VARCHAR (32) NOT NULL,
    [ADPS_PASSWORD]          VARCHAR (32) NULL,
    [ADPS_FECHA_CAMBIO]      DATETIME     NULL,
    [ADPS_FECHA_VENCIMIENTO] DATETIME     NULL,
    [ADPS_LOGIN_ADM]         VARCHAR (32) NULL
);

