CREATE TABLE [dbo].[GDEQUARE] (
    [GD_CODIGO_INSTITUCION] VARCHAR (40) NOT NULL,
    [GD_CODIGO_SUCURSAL]    VARCHAR (40) NOT NULL,
    [GD_AREA_ANTERIOR]      VARCHAR (8)  NOT NULL,
    [GD_REEST_ANTERIOR]     INT          NOT NULL,
    [GD_AREA_NUEVA]         VARCHAR (8)  NOT NULL,
    [GD_REEST_NUEVA]        INT          NOT NULL,
    [GD_CODIGO_NIVEL]       INT          NULL,
    [GD_ESTADO]             VARCHAR (2)  NOT NULL,
    [GD_USUARIO]            VARCHAR (20) NOT NULL,
    [GD_FECHA_REGISTRO]     DATETIME     NOT NULL
);

