CREATE TABLE [dbo].[GDFUNCIONARIO_AREA] (
    [GD_CODIGO_INSTITUCION]  VARCHAR (40)  NOT NULL,
    [GD_CODIGO_SUCURSAL]     VARCHAR (40)  NOT NULL,
    [GD_CODIGO_AREA]         VARCHAR (8)   NOT NULL,
    [GD_NUMERO_REESTRUCTURA] INT           NOT NULL,
    [GD_CODIGO_PERSONA]      VARCHAR (20)  NOT NULL,
    [GD_AREA_ASIGNADA]       VARCHAR (8)   NOT NULL,
    [GD_SEGUIMIENTO]         VARCHAR (2)   NOT NULL,
    [GD_OBSERVACION]         VARCHAR (255) NULL,
    [GD_USUARIO]             VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]      DATETIME      NOT NULL
);

