CREATE TABLE [dbo].[GDLISTRA] (
    [GD_CODIGO_INSTITUCION] VARCHAR (40)  NOT NULL,
    [GD_CODIGO_TRAMITE]     VARCHAR (40)  NOT NULL,
    [GD_NOMBRE]             VARCHAR (60)  NOT NULL,
    [GD_DESCRIPCION]        VARCHAR (200) NULL,
    [GD_ESTADO]             VARCHAR (8)   NOT NULL,
    [GD_UNIDAD_TIEMPO]      VARCHAR (40)  NOT NULL,
    [GD_TIEMPO_ESTIMADO]    INT           NOT NULL,
    [GD_OBSERVACION]        VARCHAR (255) NULL,
    [GD_USUARIO]            VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]     DATETIME      NOT NULL
);

