CREATE TABLE [dbo].[GDSUCURSAL] (
    [GD_CODIGO_SUCURSAL]      VARCHAR (40)  NOT NULL,
    [GD_CODIGO_INSTITUCION]   VARCHAR (40)  NOT NULL,
    [GD_NOMBRE_SUCURSAL]      VARCHAR (150) NOT NULL,
    [GD_DESCRIPCION_SUCURSAL] VARCHAR (200) NULL,
    [GD_ESTADO]               VARCHAR (40)  NOT NULL,
    [GD_DIRECCION]            VARCHAR (150) NULL,
    [GD_TELEFONOS]            VARCHAR (150) NULL,
    [GD_FAX]                  VARCHAR (100) NULL,
    [GD_EMAIL]                VARCHAR (80)  NULL,
    [GD_POBOX]                VARCHAR (50)  NULL,
    [GD_REPRESENTANTE]        VARCHAR (100) NULL,
    [GD_CARGO_REPRESENTANTE]  VARCHAR (100) NULL,
    [GD_USUARIO]              VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]       DATETIME      NOT NULL
);

