CREATE TABLE [dbo].[SGGRPUSR] (
    [SG_CODIGO_GRUPO]   VARCHAR (20)  NOT NULL,
    [SG_NOMBRE]         VARCHAR (30)  NOT NULL,
    [SG_NOMBRE_CORTO]   VARCHAR (8)   NOT NULL,
    [SG_DESCRIPCION]    VARCHAR (255) NULL,
    [SG_USUARIO]        VARCHAR (10)  NOT NULL,
    [SG_FECHA_REGISTRO] DATETIME      NOT NULL
);

