CREATE TABLE [dbo].[SGPERMISOS] (
    [GD_CODIGO_INSTITUCION] VARCHAR (40) NOT NULL,
    [GD_CODIGO_SUCURSAL]    VARCHAR (40) NOT NULL,
    [SG_CODIGO_GRUPO]       VARCHAR (20) NOT NULL,
    [SG_CODIGO_OPCION]      VARCHAR (40) NOT NULL,
    [SG_SELECT]             VARCHAR (2)  NOT NULL,
    [SG_INSERT]             VARCHAR (2)  NOT NULL,
    [SG_UPDATE]             VARCHAR (2)  NOT NULL,
    [SG_DELETE]             VARCHAR (2)  NOT NULL,
    [SG_USUARIO]            VARCHAR (20) NOT NULL,
    [SG_FECHA_REGISTRO]     DATETIME     NOT NULL
);

