ALTER TABLE [dbo].[GDFUNCIONARIO_AREA]
    ADD CONSTRAINT [FK_GDFUNCIO_REFERENCE_GDFUNCIO] FOREIGN KEY ([GD_CODIGO_PERSONA]) REFERENCES [dbo].[GDFUNCIONARIOS] ([GD_CODIGO_PERSONA]) ON DELETE NO ACTION ON UPDATE CASCADE;

