ALTER TABLE [dbo].[GDFUNCIONARIO_AREA]
    ADD CONSTRAINT [FK_GDFUNCIO_RLSH_23_GDAREUSU] FOREIGN KEY ([GD_CODIGO_AREA], [GD_NUMERO_REESTRUCTURA], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) REFERENCES [dbo].[GDAREUSU] ([GD_CODIGO_AREA], [GD_NUMERO_REESTRUCTURA], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) ON DELETE NO ACTION ON UPDATE CASCADE;

