ALTER TABLE [dbo].[GDEQUARE]
    ADD CONSTRAINT [FK_GDEQUARE_REFERENCE_GDAREUSU] FOREIGN KEY ([GD_AREA_ANTERIOR], [GD_REEST_ANTERIOR], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) REFERENCES [dbo].[GDAREUSU] ([GD_CODIGO_AREA], [GD_NUMERO_REESTRUCTURA], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) ON DELETE NO ACTION ON UPDATE CASCADE;

