ALTER TABLE [dbo].[GDASIRES]
    ADD CONSTRAINT [FK_GDASIRES_REFERENCE_GDAREUSU] FOREIGN KEY ([GD_AREA_RESPONSABLE], [GD_NUMERO_REESTRUCTURA], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) REFERENCES [dbo].[GDAREUSU] ([GD_CODIGO_AREA], [GD_NUMERO_REESTRUCTURA], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

