ALTER TABLE [dbo].[GDNUMINST]
    ADD CONSTRAINT [FK_GDNUMINS_REFERENCE_GDLISTRA] FOREIGN KEY ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDLISTRA] ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

