ALTER TABLE [dbo].[SGPERMISOS]
    ADD CONSTRAINT [FK_SGPERMIS_REFERENCE_GDSUCURS] FOREIGN KEY ([GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDSUCURSAL] ([GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

