ALTER TABLE [dbo].[SGPERMISOS]
    ADD CONSTRAINT [FK_SGPERMIS_REFERENCE_SGGRPUSR] FOREIGN KEY ([SG_CODIGO_GRUPO]) REFERENCES [dbo].[SGGRPUSR] ([SG_CODIGO_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

