ALTER TABLE [dbo].[GDCATASU]
    ADD CONSTRAINT [PK_GDCATASU] PRIMARY KEY CLUSTERED ([GD_CODIGO_ASUNTO] ASC, [GD_CODIGO_INSTITUCION] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

