ALTER TABLE [dbo].[GDSUCURSAL]
    ADD CONSTRAINT [PK_GDSUCURSAL] PRIMARY KEY CLUSTERED ([GD_CODIGO_SUCURSAL] ASC, [GD_CODIGO_INSTITUCION] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

