ALTER TABLE [dbo].[GDFUNCIONARIO_AREA]
    ADD CONSTRAINT [PK_GDFUNCIONARIO_AREA] PRIMARY KEY CLUSTERED ([GD_CODIGO_PERSONA] ASC, [GD_NUMERO_REESTRUCTURA] ASC, [GD_CODIGO_INSTITUCION] ASC, [GD_CODIGO_SUCURSAL] ASC, [GD_CODIGO_AREA] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

