CREATE NONCLUSTERED INDEX [IX_Par_Servidor_Det_1]
    ON [dbo].[Par_Servidor_Det]([Par_Servidor_Id] ASC, [Dic_Contenedor_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

