CREATE NONCLUSTERED INDEX [IX_Ver_Dominio_Version_Dominio]
    ON [dbo].[Ver_Dominio]([Ver_Version_id] ASC, [Dic_Dominio_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

