//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System; 
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato_Tipo
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private string _URL_Plantilla_Word;
        
        public Com_Contrato_Tipo()
        {
        }
        
        public Com_Contrato_Tipo(int id, string nombre, string uRL_Plantilla_Word)
        {
            this.Id = id;
            this.Nombre = nombre;
            this.URL_Plantilla_Word = uRL_Plantilla_Word;
        }
        
        public Com_Contrato_Tipo(Com_Contrato_Tipo o)
        {
            this.Id = o.Id;
            this.Nombre = o.Nombre;
            this.URL_Plantilla_Word = o.URL_Plantilla_Word;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public string URL_Plantilla_Word
        {
            get
            {
                return this._URL_Plantilla_Word;
            }
            set
            {
                this._URL_Plantilla_Word = value;
            }
        }
    }
}
