//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private int _Pla_Doc_Id;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private int _Com_Procedimiento_Id;
        
        // Comentario
        private decimal _Porcentaje_Anticipo_Ref;
        
        // Comentario
        private int _Plazo_Ref;
        
        // Comentario
        private string _Codigo_Sercop;
        
        // Comentario
        private string _Per_Personal_Resp_Exp;
        
        // Comentario
        private System.DateTime _Fecha_Cierre_Rec_Ofertas;
        
        // Comentario
        private string _Par_Razon_Social_Id_Contratista;
        
        // Comentario
        private decimal _Valor_Contrato;
        
        // Comentario
        private int _Plazo_Contrato;
        
        // Comentario
        private System.DateTime _Fecha_Inicio_Contrato;
        
        // Comentario
        private decimal _Porcentaje_Anticipo_Contrato;
        
        // Comentario
        private string _Per_Personal_Id_Admin;
        
        // Comentario
        private string _Desc_Contrata;
        
        public Com_Contrato()
        {
        }
        
        public Com_Contrato(
                    int id, 
                    int pla_Doc_Id, 
                    string estado, 
                    int com_Procedimiento_Id, 
                    decimal porcentaje_Anticipo_Ref, 
                    int plazo_Ref, 
                    string codigo_Sercop, 
                    string per_Personal_Resp_Exp, 
                    System.DateTime fecha_Cierre_Rec_Ofertas, 
                    string par_Razon_Social_Id_Contratista, 
                    decimal valor_Contrato, 
                    int plazo_Contrato, 
                    System.DateTime fecha_Inicio_Contrato, 
                    decimal porcentaje_Anticipo_Contrato, 
                    string per_Personal_Id_Admin, 
                    string desc_Contrata)
        {
            this.Id = id;
            this.Pla_Doc_Id = pla_Doc_Id;
            this.Estado = estado;
            this.Com_Procedimiento_Id = com_Procedimiento_Id;
            this.Porcentaje_Anticipo_Ref = porcentaje_Anticipo_Ref;
            this.Plazo_Ref = plazo_Ref;
            this.Codigo_Sercop = codigo_Sercop;
            this.Per_Personal_Resp_Exp = per_Personal_Resp_Exp;
            this.Fecha_Cierre_Rec_Ofertas = fecha_Cierre_Rec_Ofertas;
            this.Par_Razon_Social_Id_Contratista = par_Razon_Social_Id_Contratista;
            this.Valor_Contrato = valor_Contrato;
            this.Plazo_Contrato = plazo_Contrato;
            this.Fecha_Inicio_Contrato = fecha_Inicio_Contrato;
            this.Porcentaje_Anticipo_Contrato = porcentaje_Anticipo_Contrato;
            this.Per_Personal_Id_Admin = per_Personal_Id_Admin;
            this.Desc_Contrata = desc_Contrata;
        }
        
        public Com_Contrato(Com_Contrato o)
        {
            this.Id = o.Id;
            this.Pla_Doc_Id = o.Pla_Doc_Id;
            this.Estado = o.Estado;
            this.Com_Procedimiento_Id = o.Com_Procedimiento_Id;
            this.Porcentaje_Anticipo_Ref = o.Porcentaje_Anticipo_Ref;
            this.Plazo_Ref = o.Plazo_Ref;
            this.Codigo_Sercop = o.Codigo_Sercop;
            this.Per_Personal_Resp_Exp = o.Per_Personal_Resp_Exp;
            this.Fecha_Cierre_Rec_Ofertas = o.Fecha_Cierre_Rec_Ofertas;
            this.Par_Razon_Social_Id_Contratista = o.Par_Razon_Social_Id_Contratista;
            this.Valor_Contrato = o.Valor_Contrato;
            this.Plazo_Contrato = o.Plazo_Contrato;
            this.Fecha_Inicio_Contrato = o.Fecha_Inicio_Contrato;
            this.Porcentaje_Anticipo_Contrato = o.Porcentaje_Anticipo_Contrato;
            this.Per_Personal_Id_Admin = o.Per_Personal_Id_Admin;
            this.Desc_Contrata = o.Desc_Contrata;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public int Pla_Doc_Id
        {
            get
            {
                return this._Pla_Doc_Id;
            }
            set
            {
                this._Pla_Doc_Id = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public int Com_Procedimiento_Id
        {
            get
            {
                return this._Com_Procedimiento_Id;
            }
            set
            {
                this._Com_Procedimiento_Id = value;
            }
        }
        
        // Comentario
        public decimal Porcentaje_Anticipo_Ref
        {
            get
            {
                return this._Porcentaje_Anticipo_Ref;
            }
            set
            {
                this._Porcentaje_Anticipo_Ref = value;
            }
        }
        
        // Comentario
        public int Plazo_Ref
        {
            get
            {
                return this._Plazo_Ref;
            }
            set
            {
                this._Plazo_Ref = value;
            }
        }
        
        // Comentario
        public string Codigo_Sercop
        {
            get
            {
                return this._Codigo_Sercop;
            }
            set
            {
                this._Codigo_Sercop = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Resp_Exp
        {
            get
            {
                return this._Per_Personal_Resp_Exp;
            }
            set
            {
                this._Per_Personal_Resp_Exp = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Cierre_Rec_Ofertas
        {
            get
            {
                return this._Fecha_Cierre_Rec_Ofertas;
            }
            set
            {
                this._Fecha_Cierre_Rec_Ofertas = value;
            }
        }
        
        // Comentario
        public string Par_Razon_Social_Id_Contratista
        {
            get
            {
                return this._Par_Razon_Social_Id_Contratista;
            }
            set
            {
                this._Par_Razon_Social_Id_Contratista = value;
            }
        }
        
        // Comentario
        public decimal Valor_Contrato
        {
            get
            {
                return this._Valor_Contrato;
            }
            set
            {
                this._Valor_Contrato = value;
            }
        }
        
        // Comentario
        public int Plazo_Contrato
        {
            get
            {
                return this._Plazo_Contrato;
            }
            set
            {
                this._Plazo_Contrato = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Inicio_Contrato
        {
            get
            {
                return this._Fecha_Inicio_Contrato;
            }
            set
            {
                this._Fecha_Inicio_Contrato = value;
            }
        }
        
        // Comentario
        public decimal Porcentaje_Anticipo_Contrato
        {
            get
            {
                return this._Porcentaje_Anticipo_Contrato;
            }
            set
            {
                this._Porcentaje_Anticipo_Contrato = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Admin
        {
            get
            {
                return this._Per_Personal_Id_Admin;
            }
            set
            {
                this._Per_Personal_Id_Admin = value;
            }
        }
        
        // Comentario
        public string Desc_Contrata
        {
            get
            {
                return this._Desc_Contrata;
            }
            set
            {
                this._Desc_Contrata = value;
            }
        }
    }
}
