//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato_Oferente
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private System.DateTime _Fecha_Recepcion;
        
        // Comentario
        private int _Com_Contrato_Id;
        
        // Comentario
        private string _Per_Personal_Id_Recibe;
        
        // Comentario
        private string _Comentario;
        
        public Com_Contrato_Oferente()
        {
        }
        
        public Com_Contrato_Oferente(int id, string nombre, System.DateTime fecha_Recepcion, int com_Contrato_Id, string per_Personal_Id_Recibe, string comentario)
        {
            this.Id = id;
            this.Nombre = nombre;
            this.Fecha_Recepcion = fecha_Recepcion;
            this.Com_Contrato_Id = com_Contrato_Id;
            this.Per_Personal_Id_Recibe = per_Personal_Id_Recibe;
            this.Comentario = comentario;
        }
        
        public Com_Contrato_Oferente(Com_Contrato_Oferente o)
        {
            this.Id = o.Id;
            this.Nombre = o.Nombre;
            this.Fecha_Recepcion = o.Fecha_Recepcion;
            this.Com_Contrato_Id = o.Com_Contrato_Id;
            this.Per_Personal_Id_Recibe = o.Per_Personal_Id_Recibe;
            this.Comentario = o.Comentario;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Recepcion
        {
            get
            {
                return this._Fecha_Recepcion;
            }
            set
            {
                this._Fecha_Recepcion = value;
            }
        }
        
        // Comentario
        public int Com_Contrato_Id
        {
            get
            {
                return this._Com_Contrato_Id;
            }
            set
            {
                this._Com_Contrato_Id = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Recibe
        {
            get
            {
                return this._Per_Personal_Id_Recibe;
            }
            set
            {
                this._Per_Personal_Id_Recibe = value;
            }
        }
        
        // Comentario
        public string Comentario
        {
            get
            {
                return this._Comentario;
            }
            set
            {
                this._Comentario = value;
            }
        }
    }
}
