//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Planilla_Pago
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Fis_Planilla_Id;
        
        // Comentario
        private System.DateTime _Fecha_Pago;
        
        // Comentario
        private string _Comprobante_Pago;
        
        // Comentario
        private string _Factura_Memo_Pago;
        
        // Comentario
        private decimal _Valor_Cta_X_Cobrar;
        
        // Comentario
        private System.DateTime _Fecha_Pago_Confirmada;
        
        public Com_Planilla_Pago()
        {
        }
        
        public Com_Planilla_Pago(int id, string fis_Planilla_Id, System.DateTime fecha_Pago, string comprobante_Pago, string factura_Memo_Pago, decimal valor_Cta_X_Cobrar, System.DateTime fecha_Pago_Confirmada)
        {
            this.Id = id;
            this.Fis_Planilla_Id = fis_Planilla_Id;
            this.Fecha_Pago = fecha_Pago;
            this.Comprobante_Pago = comprobante_Pago;
            this.Factura_Memo_Pago = factura_Memo_Pago;
            this.Valor_Cta_X_Cobrar = valor_Cta_X_Cobrar;
            this.Fecha_Pago_Confirmada = fecha_Pago_Confirmada;
        }
        
        public Com_Planilla_Pago(Com_Planilla_Pago o)
        {
            this.Id = o.Id;
            this.Fis_Planilla_Id = o.Fis_Planilla_Id;
            this.Fecha_Pago = o.Fecha_Pago;
            this.Comprobante_Pago = o.Comprobante_Pago;
            this.Factura_Memo_Pago = o.Factura_Memo_Pago;
            this.Valor_Cta_X_Cobrar = o.Valor_Cta_X_Cobrar;
            this.Fecha_Pago_Confirmada = o.Fecha_Pago_Confirmada;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Fis_Planilla_Id
        {
            get
            {
                return this._Fis_Planilla_Id;
            }
            set
            {
                this._Fis_Planilla_Id = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Pago
        {
            get
            {
                return this._Fecha_Pago;
            }
            set
            {
                this._Fecha_Pago = value;
            }
        }
        
        // Comentario
        public string Comprobante_Pago
        {
            get
            {
                return this._Comprobante_Pago;
            }
            set
            {
                this._Comprobante_Pago = value;
            }
        }
        
        // Comentario
        public string Factura_Memo_Pago
        {
            get
            {
                return this._Factura_Memo_Pago;
            }
            set
            {
                this._Factura_Memo_Pago = value;
            }
        }
        
        // Comentario
        public decimal Valor_Cta_X_Cobrar
        {
            get
            {
                return this._Valor_Cta_X_Cobrar;
            }
            set
            {
                this._Valor_Cta_X_Cobrar = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Pago_Confirmada
        {
            get
            {
                return this._Fecha_Pago_Confirmada;
            }
            set
            {
                this._Fecha_Pago_Confirmada = value;
            }
        }
    }
}
