
CREATE PROCEDURE sp_lista_tipo_clientes
AS
SELECT GD_CODIGO_ITEM,
       GD_NOMBRE
FROM GDADMLIS
WHERE GD_CODIGO_TABLA='TIPOCLIENTES' AND
      GD_SECUENCIAL_ITEM<>0 AND
      GD_ACTIVO_ITEM='SI'
ORDER BY GD_NOMBRE ASC

