CREATE TABLE [dbo].[Com_Contrato] (
    [Id]                              INT             IDENTITY (1, 1) NOT NULL,
    [Pla_Doc_Id]                      INT             NOT NULL,
    [Estado]                          CHAR (3)        NOT NULL,
    [Com_Procedimiento_Id]            INT             NOT NULL,
    [Porcentaje_Anticipo_Ref]         NUMERIC (17, 4) NOT NULL,
    [Plazo_Ref]                       INT             NOT NULL,
    [Codigo_Sercop]                   VARCHAR (200)   NOT NULL,
    [Per_Personal_Resp_Exp]           VARCHAR (17)    NULL,
    [Fecha_Cierre_Rec_Ofertas]        SMALLDATETIME   NOT NULL,
    [Par_Razon_Social_Id_Contratista] VARCHAR (17)    NULL,
    [Valor_Contrato]                  NUMERIC (17, 4) NOT NULL,
    [Plazo_Contrato]                  INT             NOT NULL,
    [Fecha_Inicio_Contrato]           SMALLDATETIME   NOT NULL,
    [Porcentaje_Anticipo_Contrato]    NUMERIC (17, 4) NOT NULL,
    [Per_Personal_Id_Admin]           VARCHAR (17)    NULL,
    [Desc_Contrata]                   VARCHAR (300)   NOT NULL,
    [Fecha_Crea]                      SMALLDATETIME   NOT NULL,
    [Com_Procedimiento_Desc]          VARCHAR (250)   NULL,
    [Estado_Portal]                   CHAR (3)        NOT NULL,
    [Estado_Contratacion]             VARCHAR (250)   NOT NULL,
    [Fecha_Inicio_Elabora_Pliegos]    SMALLDATETIME   NOT NULL,
    [Fecha_Publicacion_Portal]        SMALLDATETIME   NOT NULL,
    [Fecha_Calificaciones]            SMALLDATETIME   NOT NULL,
    [Fecha_Estimada_Adjudicacion]     SMALLDATETIME   NOT NULL,
    [Fecha_Adjudicacion]              SMALLDATETIME   NOT NULL,
    [Fecha_Juridico]                  SMALLDATETIME   NOT NULL
);

