CREATE TABLE [dbo].[GDCATASU] (
    [GD_CODIGO_INSTITUCION] VARCHAR (40)  NOT NULL,
    [GD_CODIGO_ASUNTO]      VARCHAR (40)  NOT NULL,
    [GD_NOMBRE]             VARCHAR (160) NOT NULL,
    [GD_ASUNTO_PADRE]       VARCHAR (40)  NULL,
    [GD_ACTIVO]             VARCHAR (2)   NOT NULL,
    [GD_OBSERVACION]        VARCHAR (255) NULL,
    [GD_USUARIO]            VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]     DATETIME      NOT NULL
);

