CREATE TABLE [dbo].[GDINFINS] (
    [GD_CODIGO_INSTITUCION]      VARCHAR (40)  NOT NULL,
    [GD_NOMBRE]                  VARCHAR (50)  NOT NULL,
    [GD_SIGLAS]                  VARCHAR (10)  NULL,
    [GD_RUTA_LOGO]               VARCHAR (50)  NULL,
    [GD_NOMBRE_REPRESENTANTE]    VARCHAR (40)  NULL,
    [GD_DIRECCION_INSTITUCION]   VARCHAR (80)  NULL,
    [GD_TELEFONOS_INSTITUCION]   VARCHAR (20)  NULL,
    [GD_EMAIL]                   VARCHAR (40)  NULL,
    [GD_DESCRIPCION_INSTITUCION] VARCHAR (100) NULL,
    [GD_ESTADO]                  VARCHAR (40)  NOT NULL,
    [GD_OBSERVACION]             VARCHAR (255) NULL,
    [GD_USUARIO]                 VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]          DATETIME      NOT NULL
);

