CREATE TABLE [dbo].[GDRESTRA] (
    [GD_CODIGO_INSTITUCION]   VARCHAR (40)  NOT NULL,
    [GD_CODIGO_SUCURSAL]      VARCHAR (40)  NOT NULL,
    [GD_PERIODO]              VARCHAR (4)   NOT NULL,
    [GD_CODIGO_TRAMITE]       VARCHAR (40)  NOT NULL,
    [GD_NUMERO]               INT           NOT NULL,
    [GD_SECUENCIAL_RESPUESTA] INT           NOT NULL,
    [GD_DISPUESTO_POR]        VARCHAR (40)  NULL,
    [GD_NUMERO_TRAMITE]       VARCHAR (40)  NULL,
    [GD_FECHA_RESPUESTA]      DATETIME      NULL,
    [GD_TIPO_DOCUMENTO]       VARCHAR (40)  NULL,
    [GD_UBICACION_FISICA]     VARCHAR (40)  NULL,
    [GD_ANEXOS]               VARCHAR (2)   NOT NULL,
    [GD_OBSERVACION]          VARCHAR (255) NULL,
    [GD_RESULTADO]            TEXT          NULL,
    [GD_USUARIO]              VARCHAR (20)  NOT NULL,
    [GD_FECHA_REGISTRO]       DATETIME      NOT NULL
);

