CREATE TABLE [dbo].[GDTRAMITE_FUNCIONARIO] (
    [GD_CODIGO_TRAMITE]     VARCHAR (40) NOT NULL,
    [GD_CODIGO_INSTITUCION] VARCHAR (40) NOT NULL,
    [GD_CODIGO_PERSONA]     VARCHAR (20) NOT NULL,
    [GD_USUARIO]            VARCHAR (20) NOT NULL,
    [GD_FECHA_REGISTRO]     DATETIME     NOT NULL
);

