CREATE TABLE [dbo].[SGMIEMBROS] (
    [GD_CODIGO_INSTITUCION] VARCHAR (40) NOT NULL,
    [GD_CODIGO_SUCURSAL]    VARCHAR (40) NOT NULL,
    [SG_CODIGO_GRUPO]       VARCHAR (20) NOT NULL,
    [GD_CODIGO_PERSONA]     VARCHAR (20) NOT NULL,
    [SG_USUARIO]            VARCHAR (20) NOT NULL,
    [SG_FECHA_REGISTRO]     DATETIME     NOT NULL
);

