//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Lote
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private string _URL_Archivo_IN;
        
        // Comentario
        private int _Pla_Lote_Tipo_Id;
        
        // Comentario
        private string _Resultado;
        
        // Comentario
        private string _URL_Archivo_OUT;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private System.DateTime _Lote_Fecha;
        
        public Pla_Lote()
        {
        }
        
        public Pla_Lote(int id, string codigo, string nombre, string uRL_Archivo_IN, int pla_Lote_Tipo_Id, string resultado, string uRL_Archivo_OUT, string estado, System.DateTime lote_Fecha)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Nombre = nombre;
            this.URL_Archivo_IN = uRL_Archivo_IN;
            this.Pla_Lote_Tipo_Id = pla_Lote_Tipo_Id;
            this.Resultado = resultado;
            this.URL_Archivo_OUT = uRL_Archivo_OUT;
            this.Estado = estado;
            this.Lote_Fecha = lote_Fecha;
        }
        
        public Pla_Lote(Pla_Lote o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Nombre = o.Nombre;
            this.URL_Archivo_IN = o.URL_Archivo_IN;
            this.Pla_Lote_Tipo_Id = o.Pla_Lote_Tipo_Id;
            this.Resultado = o.Resultado;
            this.URL_Archivo_OUT = o.URL_Archivo_OUT;
            this.Estado = o.Estado;
            this.Lote_Fecha = o.Lote_Fecha;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public string URL_Archivo_IN
        {
            get
            {
                return this._URL_Archivo_IN;
            }
            set
            {
                this._URL_Archivo_IN = value;
            }
        }
        
        // Comentario
        public int Pla_Lote_Tipo_Id
        {
            get
            {
                return this._Pla_Lote_Tipo_Id;
            }
            set
            {
                this._Pla_Lote_Tipo_Id = value;
            }
        }
        
        // Comentario
        public string Resultado
        {
            get
            {
                return this._Resultado;
            }
            set
            {
                this._Resultado = value;
            }
        }
        
        // Comentario
        public string URL_Archivo_OUT
        {
            get
            {
                return this._URL_Archivo_OUT;
            }
            set
            {
                this._URL_Archivo_OUT = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public System.DateTime Lote_Fecha
        {
            get
            {
                return this._Lote_Fecha;
            }
            set
            {
                this._Lote_Fecha = value;
            }
        }
    }
}
