//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Doc
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private string _Tipo;
        
        // Comentario
        private System.DateTime _Fecha_Solicita;
        
        // Comentario
        private string _Per_Personal_Id_Solicita;
        
        // Comentario
        private string _Area_Codigo_Solicita;
        
        // Comentario
        private string _Descripcion;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private string _Per_Personal_Id_Crea;
        
        // Comentario
        private string _Per_Personal_Id_Modifica;
        
        // Comentario
        private decimal _Valor_Solicita;
        
        // Comentario
        private string _Per_Personal_Id_Planifica;
        
        // Comentario
        private string _Esta_Planificada;
        
        // Comentario
        private string _Per_Personal_Id_Contrata;
        
        // Comentario
        private string _Esta_Contratada;
        
        // Comentario
        private string _PAC_Linea;
        
        // Comentario
        private string _CPC_Codigo;
        
        // Comentario
        private System.DateTime _Fecha_Contrata;
        
        // Comentario
        private System.DateTime _Fecha_Planifica;
        
        // Comentario
        private string _Cedula_Presup_Codigo;
        
        // Comentario
        private string _Contrata_Desc;
        
        // Comentario
        private int _Pla_Tarea_Id;
        
        // Comentario
        private string _Proyecto_Tipo;
        
        // Comentario
        private int _Pla_Doc_Id_Principal;
        
        // Comentario
        private int _Com_Procedimiento_Id;
        
        // Comentario
        private string _Per_Personal_Id_Presupuesta;
        
        // Comentario
        private string _Esta_Presupuestada;
        
        // Comentario
        private System.DateTime _Fecha_Presupuesta;
        
        // Comentario
        private string _Desc_Presupuesta;
        
        // Comentario
        private string _Desc_Planifica;
        
        // Comentario
        private string _Desc_Solicita;
        
        // Comentario
        private string _Per_Personal_Nombre_Solicita;
        
        // Comentario
        private string _Area_Nombre_Solicita;
        
        // Comentario
        private string _Per_Personal_Nombre_Crea;
        
        // Comentario
        private string _Per_Personal_Nombre_Modifica;
        
        // Comentario
        private string _Per_Personal_Nombre_Planifica;
        
        // Comentario
        private string _Per_Personal_Nombre_Contrata;
        
        // Comentario
        private decimal _Valor_Suma_Movs;
        
        // Comentario
        private string _Pla_Tarea_Nombre;
        
        // Comentario
        private int _Pla_Cta_Id;
        
        // Comentario
        private string _Pla_Cta_Codigo;
        
        // Comentario
        private string _Pla_Cta_Nombre;
        
        // Comentario
        private string _Estado_Proceso;
        
        // Comentario
        private string _Proyecto_Tipo_Nombre;
        
        // Comentario
        private string _Pla_Doc_Codigo_Principal;
        
        // Comentario
        private string _Com_Procedimiento_Nombre;
        
        // Comentario
        private string _Per_Personal_Nombre_Presupuesta;
        
        public Pla_Doc()
        {
        }
        
        public Pla_Doc(
                    int id, 
                    string codigo, 
                    string tipo, 
                    System.DateTime fecha_Solicita, 
                    string per_Personal_Id_Solicita, 
                    string area_Codigo_Solicita, 
                    string descripcion, 
                    string estado, 
                    string per_Personal_Id_Crea, 
                    string per_Personal_Id_Modifica, 
                    decimal valor_Solicita, 
                    string per_Personal_Id_Planifica, 
                    string esta_Planificada, 
                    string per_Personal_Id_Contrata, 
                    string esta_Contratada, 
                    string pAC_Linea, 
                    string cPC_Codigo, 
                    System.DateTime fecha_Contrata, 
                    System.DateTime fecha_Planifica, 
                    string cedula_Presup_Codigo, 
                    string contrata_Desc, 
                    int pla_Tarea_Id, 
                    string proyecto_Tipo, 
                    int pla_Doc_Id_Principal, 
                    int com_Procedimiento_Id, 
                    string per_Personal_Id_Presupuesta, 
                    string esta_Presupuestada, 
                    System.DateTime fecha_Presupuesta, 
                    string desc_Presupuesta, 
                    string desc_Planifica, 
                    string desc_Solicita, 
                    string per_Personal_Nombre_Solicita, 
                    string area_Nombre_Solicita, 
                    string per_Personal_Nombre_Crea, 
                    string per_Personal_Nombre_Modifica, 
                    string per_Personal_Nombre_Planifica, 
                    string per_Personal_Nombre_Contrata, 
                    decimal valor_Suma_Movs, 
                    string pla_Tarea_Nombre, 
                    int pla_Cta_Id, 
                    string pla_Cta_Codigo, 
                    string pla_Cta_Nombre, 
                    string estado_Proceso, 
                    string proyecto_Tipo_Nombre, 
                    string pla_Doc_Codigo_Principal, 
                    string com_Procedimiento_Nombre, 
                    string per_Personal_Nombre_Presupuesta)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Tipo = tipo;
            this.Fecha_Solicita = fecha_Solicita;
            this.Per_Personal_Id_Solicita = per_Personal_Id_Solicita;
            this.Area_Codigo_Solicita = area_Codigo_Solicita;
            this.Descripcion = descripcion;
            this.Estado = estado;
            this.Per_Personal_Id_Crea = per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = per_Personal_Id_Modifica;
            this.Valor_Solicita = valor_Solicita;
            this.Per_Personal_Id_Planifica = per_Personal_Id_Planifica;
            this.Esta_Planificada = esta_Planificada;
            this.Per_Personal_Id_Contrata = per_Personal_Id_Contrata;
            this.Esta_Contratada = esta_Contratada;
            this.PAC_Linea = pAC_Linea;
            this.CPC_Codigo = cPC_Codigo;
            this.Fecha_Contrata = fecha_Contrata;
            this.Fecha_Planifica = fecha_Planifica;
            this.Cedula_Presup_Codigo = cedula_Presup_Codigo;
            this.Contrata_Desc = contrata_Desc;
            this.Pla_Tarea_Id = pla_Tarea_Id;
            this.Proyecto_Tipo = proyecto_Tipo;
            this.Pla_Doc_Id_Principal = pla_Doc_Id_Principal;
            this.Com_Procedimiento_Id = com_Procedimiento_Id;
            this.Per_Personal_Id_Presupuesta = per_Personal_Id_Presupuesta;
            this.Esta_Presupuestada = esta_Presupuestada;
            this.Fecha_Presupuesta = fecha_Presupuesta;
            this.Desc_Presupuesta = desc_Presupuesta;
            this.Desc_Planifica = desc_Planifica;
            this.Desc_Solicita = desc_Solicita;
            this.Per_Personal_Nombre_Solicita = per_Personal_Nombre_Solicita;
            this.Area_Nombre_Solicita = area_Nombre_Solicita;
            this.Per_Personal_Nombre_Crea = per_Personal_Nombre_Crea;
            this.Per_Personal_Nombre_Modifica = per_Personal_Nombre_Modifica;
            this.Per_Personal_Nombre_Planifica = per_Personal_Nombre_Planifica;
            this.Per_Personal_Nombre_Contrata = per_Personal_Nombre_Contrata;
            this.Valor_Suma_Movs = valor_Suma_Movs;
            this.Pla_Tarea_Nombre = pla_Tarea_Nombre;
            this.Pla_Cta_Id = pla_Cta_Id;
            this.Pla_Cta_Codigo = pla_Cta_Codigo;
            this.Pla_Cta_Nombre = pla_Cta_Nombre;
            this.Estado_Proceso = estado_Proceso;
            this.Proyecto_Tipo_Nombre = proyecto_Tipo_Nombre;
            this.Pla_Doc_Codigo_Principal = pla_Doc_Codigo_Principal;
            this.Com_Procedimiento_Nombre = com_Procedimiento_Nombre;
            this.Per_Personal_Nombre_Presupuesta = per_Personal_Nombre_Presupuesta;
        }
        
        public Pla_Doc(Pla_Doc o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Tipo = o.Tipo;
            this.Fecha_Solicita = o.Fecha_Solicita;
            this.Per_Personal_Id_Solicita = o.Per_Personal_Id_Solicita;
            this.Area_Codigo_Solicita = o.Area_Codigo_Solicita;
            this.Descripcion = o.Descripcion;
            this.Estado = o.Estado;
            this.Per_Personal_Id_Crea = o.Per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = o.Per_Personal_Id_Modifica;
            this.Valor_Solicita = o.Valor_Solicita;
            this.Per_Personal_Id_Planifica = o.Per_Personal_Id_Planifica;
            this.Esta_Planificada = o.Esta_Planificada;
            this.Per_Personal_Id_Contrata = o.Per_Personal_Id_Contrata;
            this.Esta_Contratada = o.Esta_Contratada;
            this.PAC_Linea = o.PAC_Linea;
            this.CPC_Codigo = o.CPC_Codigo;
            this.Fecha_Contrata = o.Fecha_Contrata;
            this.Fecha_Planifica = o.Fecha_Planifica;
            this.Cedula_Presup_Codigo = o.Cedula_Presup_Codigo;
            this.Contrata_Desc = o.Contrata_Desc;
            this.Pla_Tarea_Id = o.Pla_Tarea_Id;
            this.Proyecto_Tipo = o.Proyecto_Tipo;
            this.Pla_Doc_Id_Principal = o.Pla_Doc_Id_Principal;
            this.Com_Procedimiento_Id = o.Com_Procedimiento_Id;
            this.Per_Personal_Id_Presupuesta = o.Per_Personal_Id_Presupuesta;
            this.Esta_Presupuestada = o.Esta_Presupuestada;
            this.Fecha_Presupuesta = o.Fecha_Presupuesta;
            this.Desc_Presupuesta = o.Desc_Presupuesta;
            this.Desc_Planifica = o.Desc_Planifica;
            this.Desc_Solicita = o.Desc_Solicita;
            this.Per_Personal_Nombre_Solicita = o.Per_Personal_Nombre_Solicita;
            this.Area_Nombre_Solicita = o.Area_Nombre_Solicita;
            this.Per_Personal_Nombre_Crea = o.Per_Personal_Nombre_Crea;
            this.Per_Personal_Nombre_Modifica = o.Per_Personal_Nombre_Modifica;
            this.Per_Personal_Nombre_Planifica = o.Per_Personal_Nombre_Planifica;
            this.Per_Personal_Nombre_Contrata = o.Per_Personal_Nombre_Contrata;
            this.Valor_Suma_Movs = o.Valor_Suma_Movs;
            this.Pla_Tarea_Nombre = o.Pla_Tarea_Nombre;
            this.Pla_Cta_Id = o.Pla_Cta_Id;
            this.Pla_Cta_Codigo = o.Pla_Cta_Codigo;
            this.Pla_Cta_Nombre = o.Pla_Cta_Nombre;
            this.Estado_Proceso = o.Estado_Proceso;
            this.Proyecto_Tipo_Nombre = o.Proyecto_Tipo_Nombre;
            this.Pla_Doc_Codigo_Principal = o.Pla_Doc_Codigo_Principal;
            this.Com_Procedimiento_Nombre = o.Com_Procedimiento_Nombre;
            this.Per_Personal_Nombre_Presupuesta = o.Per_Personal_Nombre_Presupuesta;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Solicita
        {
            get
            {
                return this._Fecha_Solicita;
            }
            set
            {
                this._Fecha_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Solicita
        {
            get
            {
                return this._Per_Personal_Id_Solicita;
            }
            set
            {
                this._Per_Personal_Id_Solicita = value;
            }
        }
        
        // Comentario
        public string Area_Codigo_Solicita
        {
            get
            {
                return this._Area_Codigo_Solicita;
            }
            set
            {
                this._Area_Codigo_Solicita = value;
            }
        }
        
        // Comentario
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Crea
        {
            get
            {
                return this._Per_Personal_Id_Crea;
            }
            set
            {
                this._Per_Personal_Id_Crea = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Modifica
        {
            get
            {
                return this._Per_Personal_Id_Modifica;
            }
            set
            {
                this._Per_Personal_Id_Modifica = value;
            }
        }
        
        // Comentario
        public decimal Valor_Solicita
        {
            get
            {
                return this._Valor_Solicita;
            }
            set
            {
                this._Valor_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Planifica
        {
            get
            {
                return this._Per_Personal_Id_Planifica;
            }
            set
            {
                this._Per_Personal_Id_Planifica = value;
            }
        }
        
        // Comentario
        public string Esta_Planificada
        {
            get
            {
                return this._Esta_Planificada;
            }
            set
            {
                this._Esta_Planificada = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Contrata
        {
            get
            {
                return this._Per_Personal_Id_Contrata;
            }
            set
            {
                this._Per_Personal_Id_Contrata = value;
            }
        }
        
        // Comentario
        public string Esta_Contratada
        {
            get
            {
                return this._Esta_Contratada;
            }
            set
            {
                this._Esta_Contratada = value;
            }
        }
        
        // Comentario
        public string PAC_Linea
        {
            get
            {
                return this._PAC_Linea;
            }
            set
            {
                this._PAC_Linea = value;
            }
        }
        
        // Comentario
        public string CPC_Codigo
        {
            get
            {
                return this._CPC_Codigo;
            }
            set
            {
                this._CPC_Codigo = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Contrata
        {
            get
            {
                return this._Fecha_Contrata;
            }
            set
            {
                this._Fecha_Contrata = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Planifica
        {
            get
            {
                return this._Fecha_Planifica;
            }
            set
            {
                this._Fecha_Planifica = value;
            }
        }
        
        // Comentario
        public string Cedula_Presup_Codigo
        {
            get
            {
                return this._Cedula_Presup_Codigo;
            }
            set
            {
                this._Cedula_Presup_Codigo = value;
            }
        }
        
        // Comentario
        public string Contrata_Desc
        {
            get
            {
                return this._Contrata_Desc;
            }
            set
            {
                this._Contrata_Desc = value;
            }
        }
        
        // Comentario
        public int Pla_Tarea_Id
        {
            get
            {
                return this._Pla_Tarea_Id;
            }
            set
            {
                this._Pla_Tarea_Id = value;
            }
        }
        
        // Comentario
        public string Proyecto_Tipo
        {
            get
            {
                return this._Proyecto_Tipo;
            }
            set
            {
                this._Proyecto_Tipo = value;
            }
        }
        
        // Comentario
        public int Pla_Doc_Id_Principal
        {
            get
            {
                return this._Pla_Doc_Id_Principal;
            }
            set
            {
                this._Pla_Doc_Id_Principal = value;
            }
        }
        
        // Comentario
        public int Com_Procedimiento_Id
        {
            get
            {
                return this._Com_Procedimiento_Id;
            }
            set
            {
                this._Com_Procedimiento_Id = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Presupuesta
        {
            get
            {
                return this._Per_Personal_Id_Presupuesta;
            }
            set
            {
                this._Per_Personal_Id_Presupuesta = value;
            }
        }
        
        // Comentario
        public string Esta_Presupuestada
        {
            get
            {
                return this._Esta_Presupuestada;
            }
            set
            {
                this._Esta_Presupuestada = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Presupuesta
        {
            get
            {
                return this._Fecha_Presupuesta;
            }
            set
            {
                this._Fecha_Presupuesta = value;
            }
        }
        
        // Comentario
        public string Desc_Presupuesta
        {
            get
            {
                return this._Desc_Presupuesta;
            }
            set
            {
                this._Desc_Presupuesta = value;
            }
        }
        
        // Comentario
        public string Desc_Planifica
        {
            get
            {
                return this._Desc_Planifica;
            }
            set
            {
                this._Desc_Planifica = value;
            }
        }
        
        // Comentario
        public string Desc_Solicita
        {
            get
            {
                return this._Desc_Solicita;
            }
            set
            {
                this._Desc_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Solicita
        {
            get
            {
                return this._Per_Personal_Nombre_Solicita;
            }
            set
            {
                this._Per_Personal_Nombre_Solicita = value;
            }
        }
        
        // Comentario
        public string Area_Nombre_Solicita
        {
            get
            {
                return this._Area_Nombre_Solicita;
            }
            set
            {
                this._Area_Nombre_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Crea
        {
            get
            {
                return this._Per_Personal_Nombre_Crea;
            }
            set
            {
                this._Per_Personal_Nombre_Crea = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Modifica
        {
            get
            {
                return this._Per_Personal_Nombre_Modifica;
            }
            set
            {
                this._Per_Personal_Nombre_Modifica = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Planifica
        {
            get
            {
                return this._Per_Personal_Nombre_Planifica;
            }
            set
            {
                this._Per_Personal_Nombre_Planifica = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Contrata
        {
            get
            {
                return this._Per_Personal_Nombre_Contrata;
            }
            set
            {
                this._Per_Personal_Nombre_Contrata = value;
            }
        }
        
        // Comentario
        public decimal Valor_Suma_Movs
        {
            get
            {
                return this._Valor_Suma_Movs;
            }
            set
            {
                this._Valor_Suma_Movs = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Nombre
        {
            get
            {
                return this._Pla_Tarea_Nombre;
            }
            set
            {
                this._Pla_Tarea_Nombre = value;
            }
        }
        
        // Comentario
        public int Pla_Cta_Id
        {
            get
            {
                return this._Pla_Cta_Id;
            }
            set
            {
                this._Pla_Cta_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Codigo
        {
            get
            {
                return this._Pla_Cta_Codigo;
            }
            set
            {
                this._Pla_Cta_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Nombre
        {
            get
            {
                return this._Pla_Cta_Nombre;
            }
            set
            {
                this._Pla_Cta_Nombre = value;
            }
        }
        
        // Comentario
        public string Estado_Proceso
        {
            get
            {
                return this._Estado_Proceso;
            }
            set
            {
                this._Estado_Proceso = value;
            }
        }
        
        // Comentario
        public string Proyecto_Tipo_Nombre
        {
            get
            {
                return this._Proyecto_Tipo_Nombre;
            }
            set
            {
                this._Proyecto_Tipo_Nombre = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_Codigo_Principal
        {
            get
            {
                return this._Pla_Doc_Codigo_Principal;
            }
            set
            {
                this._Pla_Doc_Codigo_Principal = value;
            }
        }
        
        // Comentario
        public string Com_Procedimiento_Nombre
        {
            get
            {
                return this._Com_Procedimiento_Nombre;
            }
            set
            {
                this._Com_Procedimiento_Nombre = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Presupuesta
        {
            get
            {
                return this._Per_Personal_Nombre_Presupuesta;
            }
            set
            {
                this._Per_Personal_Nombre_Presupuesta = value;
            }
        }
    }
}
