//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Mov
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private int _Pla_Poa_Id;
        
        // Comentario
        private int _Pla_Doc_Id;
        
        // Comentario
        private int _Orden;
        
        // Comentario
        private decimal _Valor;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private string _Tipo;
        
        // Comentario
        private int _Pla_Tarea_Id;
        
        // Comentario
        private string _Pla_Tarea_Nombre;
        
        // Comentario
        private int _Pla_Partida_Id;
        
        // Comentario
        private string _Pla_Partida_Codigo;
        
        // Comentario
        private string _Pla_Partida_Nombre;
        
        // Comentario
        private string _Pla_Doc_Tipo;
        
        // Comentario
        private System.DateTime _Pla_Doc_Fecha;
        
        // Comentario
        private string _Pla_Doc_Codigo;
        
        public Pla_Mov()
        {
        }
        
        public Pla_Mov(
                    int id, 
                    string codigo, 
                    int pla_Poa_Id, 
                    int pla_Doc_Id, 
                    int orden, 
                    decimal valor, 
                    string estado, 
                    string tipo, 
                    int pla_Tarea_Id, 
                    string pla_Tarea_Nombre, 
                    int pla_Partida_Id, 
                    string pla_Partida_Codigo, 
                    string pla_Partida_Nombre, 
                    string pla_Doc_Tipo, 
                    System.DateTime pla_Doc_Fecha, 
                    string pla_Doc_Codigo)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Pla_Poa_Id = pla_Poa_Id;
            this.Pla_Doc_Id = pla_Doc_Id;
            this.Orden = orden;
            this.Valor = valor;
            this.Estado = estado;
            this.Tipo = tipo;
            this.Pla_Tarea_Id = pla_Tarea_Id;
            this.Pla_Tarea_Nombre = pla_Tarea_Nombre;
            this.Pla_Partida_Id = pla_Partida_Id;
            this.Pla_Partida_Codigo = pla_Partida_Codigo;
            this.Pla_Partida_Nombre = pla_Partida_Nombre;
            this.Pla_Doc_Tipo = pla_Doc_Tipo;
            this.Pla_Doc_Fecha = pla_Doc_Fecha;
            this.Pla_Doc_Codigo = pla_Doc_Codigo;
        }
        
        public Pla_Mov(Pla_Mov o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Pla_Poa_Id = o.Pla_Poa_Id;
            this.Pla_Doc_Id = o.Pla_Doc_Id;
            this.Orden = o.Orden;
            this.Valor = o.Valor;
            this.Estado = o.Estado;
            this.Tipo = o.Tipo;
            this.Pla_Tarea_Id = o.Pla_Tarea_Id;
            this.Pla_Tarea_Nombre = o.Pla_Tarea_Nombre;
            this.Pla_Partida_Id = o.Pla_Partida_Id;
            this.Pla_Partida_Codigo = o.Pla_Partida_Codigo;
            this.Pla_Partida_Nombre = o.Pla_Partida_Nombre;
            this.Pla_Doc_Tipo = o.Pla_Doc_Tipo;
            this.Pla_Doc_Fecha = o.Pla_Doc_Fecha;
            this.Pla_Doc_Codigo = o.Pla_Doc_Codigo;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public int Pla_Poa_Id
        {
            get
            {
                return this._Pla_Poa_Id;
            }
            set
            {
                this._Pla_Poa_Id = value;
            }
        }
        
        // Comentario
        public int Pla_Doc_Id
        {
            get
            {
                return this._Pla_Doc_Id;
            }
            set
            {
                this._Pla_Doc_Id = value;
            }
        }
        
        // Comentario
        public int Orden
        {
            get
            {
                return this._Orden;
            }
            set
            {
                this._Orden = value;
            }
        }
        
        // Comentario
        public decimal Valor
        {
            get
            {
                return this._Valor;
            }
            set
            {
                this._Valor = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
            }
        }
        
        // Comentario
        public int Pla_Tarea_Id
        {
            get
            {
                return this._Pla_Tarea_Id;
            }
            set
            {
                this._Pla_Tarea_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Nombre
        {
            get
            {
                return this._Pla_Tarea_Nombre;
            }
            set
            {
                this._Pla_Tarea_Nombre = value;
            }
        }
        
        // Comentario
        public int Pla_Partida_Id
        {
            get
            {
                return this._Pla_Partida_Id;
            }
            set
            {
                this._Pla_Partida_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Partida_Codigo
        {
            get
            {
                return this._Pla_Partida_Codigo;
            }
            set
            {
                this._Pla_Partida_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Partida_Nombre
        {
            get
            {
                return this._Pla_Partida_Nombre;
            }
            set
            {
                this._Pla_Partida_Nombre = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_Tipo
        {
            get
            {
                return this._Pla_Doc_Tipo;
            }
            set
            {
                this._Pla_Doc_Tipo = value;
            }
        }
        
        // Comentario
        public System.DateTime Pla_Doc_Fecha
        {
            get
            {
                return this._Pla_Doc_Fecha;
            }
            set
            {
                this._Pla_Doc_Fecha = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_Codigo
        {
            get
            {
                return this._Pla_Doc_Codigo;
            }
            set
            {
                this._Pla_Doc_Codigo = value;
            }
        }
    }
}
