//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Doc
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private string _Tipo;
        
        // Comentario
        private System.DateTime _Fecha;
        
        // Comentario
        private string _Per_Personal_Id_Solicita;
        
        // Comentario
        private string _Area_Solicita;
        
        // Comentario
        private string _Descripcion;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private string _Per_Personal_Id_Crea;
        
        // Comentario
        private string _Per_Personal_Id_Modifica;
        
        public Pla_Doc()
        {
        }
        
        public Pla_Doc(int id, string codigo, string tipo, System.DateTime fecha, string per_Personal_Id_Solicita, string area_Solicita, string descripcion, string estado, string per_Personal_Id_Crea, string per_Personal_Id_Modifica)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Tipo = tipo;
            this.Fecha = fecha;
            this.Per_Personal_Id_Solicita = per_Personal_Id_Solicita;
            this.Area_Solicita = area_Solicita;
            this.Descripcion = descripcion;
            this.Estado = estado;
            this.Per_Personal_Id_Crea = per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = per_Personal_Id_Modifica;
        }
        
        public Pla_Doc(Pla_Doc o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Tipo = o.Tipo;
            this.Fecha = o.Fecha;
            this.Per_Personal_Id_Solicita = o.Per_Personal_Id_Solicita;
            this.Area_Solicita = o.Area_Solicita;
            this.Descripcion = o.Descripcion;
            this.Estado = o.Estado;
            this.Per_Personal_Id_Crea = o.Per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = o.Per_Personal_Id_Modifica;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha
        {
            get
            {
                return this._Fecha;
            }
            set
            {
                this._Fecha = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Solicita
        {
            get
            {
                return this._Per_Personal_Id_Solicita;
            }
            set
            {
                this._Per_Personal_Id_Solicita = value;
            }
        }
        
        // Comentario
        public string Area_Solicita
        {
            get
            {
                return this._Area_Solicita;
            }
            set
            {
                this._Area_Solicita = value;
            }
        }
        
        // Comentario
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Crea
        {
            get
            {
                return this._Per_Personal_Id_Crea;
            }
            set
            {
                this._Per_Personal_Id_Crea = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Modifica
        {
            get
            {
                return this._Per_Personal_Id_Modifica;
            }
            set
            {
                this._Per_Personal_Id_Modifica = value;
            }
        }
    }
}
