//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Doc
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private string _Tipo;
        
        // Comentario
        private System.DateTime _Fecha_Solicita;
        
        // Comentario
        private string _Per_Personal_Id_Solicita;
        
        // Comentario
        private string _Area_Codigo_Solicita;
        
        // Comentario
        private string _Descripcion;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private string _Per_Personal_Id_Crea;
        
        // Comentario
        private string _Per_Personal_Id_Modifica;
        
        // Comentario
        private decimal _Valor_Solicita;
        
        // Comentario
        private string _Per_Personal_Id_Planifica;
        
        // Comentario
        private string _Esta_Planificada;
        
        // Comentario
        private string _Per_Personal_Id_Contrata;
        
        // Comentario
        private string _Esta_Contratada;
        
        // Comentario
        private string _PAC_Linea;
        
        // Comentario
        private string _CPC_Codigo;
        
        // Comentario
        private System.DateTime _Fecha_Contrata;
        
        // Comentario
        private System.DateTime _Fecha_Planifica;
        
        // Comentario
        private string _Per_Personal_Nombre_Solicita;
        
        // Comentario
        private string _Area_Nombre_Solicita;
        
        // Comentario
        private string _Per_Personal_Nombre_Crea;
        
        // Comentario
        private string _Per_Personal_Nombre_Modifica;
        
        // Comentario
        private string _Per_Personal_Nombre_Planifica;
        
        // Comentario
        private string _Per_Personal_Nombre_Contrata;
        
        // Comentario
        private decimal _Valor_Suma_Movs;
        
        public Pla_Doc()
        {
        }
        
        public Pla_Doc(
                    int id, 
                    string codigo, 
                    string tipo, 
                    System.DateTime fecha_Solicita, 
                    string per_Personal_Id_Solicita, 
                    string area_Codigo_Solicita, 
                    string descripcion, 
                    string estado, 
                    string per_Personal_Id_Crea, 
                    string per_Personal_Id_Modifica, 
                    decimal valor_Solicita, 
                    string per_Personal_Id_Planifica, 
                    string esta_Planificada, 
                    string per_Personal_Id_Contrata, 
                    string esta_Contratada, 
                    string pAC_Linea, 
                    string cPC_Codigo, 
                    System.DateTime fecha_Contrata, 
                    System.DateTime fecha_Planifica, 
                    string per_Personal_Nombre_Solicita, 
                    string area_Nombre_Solicita, 
                    string per_Personal_Nombre_Crea, 
                    string per_Personal_Nombre_Modifica, 
                    string per_Personal_Nombre_Planifica, 
                    string per_Personal_Nombre_Contrata, 
                    decimal valor_Suma_Movs)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Tipo = tipo;
            this.Fecha_Solicita = fecha_Solicita;
            this.Per_Personal_Id_Solicita = per_Personal_Id_Solicita;
            this.Area_Codigo_Solicita = area_Codigo_Solicita;
            this.Descripcion = descripcion;
            this.Estado = estado;
            this.Per_Personal_Id_Crea = per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = per_Personal_Id_Modifica;
            this.Valor_Solicita = valor_Solicita;
            this.Per_Personal_Id_Planifica = per_Personal_Id_Planifica;
            this.Esta_Planificada = esta_Planificada;
            this.Per_Personal_Id_Contrata = per_Personal_Id_Contrata;
            this.Esta_Contratada = esta_Contratada;
            this.PAC_Linea = pAC_Linea;
            this.CPC_Codigo = cPC_Codigo;
            this.Fecha_Contrata = fecha_Contrata;
            this.Fecha_Planifica = fecha_Planifica;
            this.Per_Personal_Nombre_Solicita = per_Personal_Nombre_Solicita;
            this.Area_Nombre_Solicita = area_Nombre_Solicita;
            this.Per_Personal_Nombre_Crea = per_Personal_Nombre_Crea;
            this.Per_Personal_Nombre_Modifica = per_Personal_Nombre_Modifica;
            this.Per_Personal_Nombre_Planifica = per_Personal_Nombre_Planifica;
            this.Per_Personal_Nombre_Contrata = per_Personal_Nombre_Contrata;
            this.Valor_Suma_Movs = valor_Suma_Movs;
        }
        
        public Pla_Doc(Pla_Doc o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Tipo = o.Tipo;
            this.Fecha_Solicita = o.Fecha_Solicita;
            this.Per_Personal_Id_Solicita = o.Per_Personal_Id_Solicita;
            this.Area_Codigo_Solicita = o.Area_Codigo_Solicita;
            this.Descripcion = o.Descripcion;
            this.Estado = o.Estado;
            this.Per_Personal_Id_Crea = o.Per_Personal_Id_Crea;
            this.Per_Personal_Id_Modifica = o.Per_Personal_Id_Modifica;
            this.Valor_Solicita = o.Valor_Solicita;
            this.Per_Personal_Id_Planifica = o.Per_Personal_Id_Planifica;
            this.Esta_Planificada = o.Esta_Planificada;
            this.Per_Personal_Id_Contrata = o.Per_Personal_Id_Contrata;
            this.Esta_Contratada = o.Esta_Contratada;
            this.PAC_Linea = o.PAC_Linea;
            this.CPC_Codigo = o.CPC_Codigo;
            this.Fecha_Contrata = o.Fecha_Contrata;
            this.Fecha_Planifica = o.Fecha_Planifica;
            this.Per_Personal_Nombre_Solicita = o.Per_Personal_Nombre_Solicita;
            this.Area_Nombre_Solicita = o.Area_Nombre_Solicita;
            this.Per_Personal_Nombre_Crea = o.Per_Personal_Nombre_Crea;
            this.Per_Personal_Nombre_Modifica = o.Per_Personal_Nombre_Modifica;
            this.Per_Personal_Nombre_Planifica = o.Per_Personal_Nombre_Planifica;
            this.Per_Personal_Nombre_Contrata = o.Per_Personal_Nombre_Contrata;
            this.Valor_Suma_Movs = o.Valor_Suma_Movs;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Solicita
        {
            get
            {
                return this._Fecha_Solicita;
            }
            set
            {
                this._Fecha_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Solicita
        {
            get
            {
                return this._Per_Personal_Id_Solicita;
            }
            set
            {
                this._Per_Personal_Id_Solicita = value;
            }
        }
        
        // Comentario
        public string Area_Codigo_Solicita
        {
            get
            {
                return this._Area_Codigo_Solicita;
            }
            set
            {
                this._Area_Codigo_Solicita = value;
            }
        }
        
        // Comentario
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Crea
        {
            get
            {
                return this._Per_Personal_Id_Crea;
            }
            set
            {
                this._Per_Personal_Id_Crea = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Modifica
        {
            get
            {
                return this._Per_Personal_Id_Modifica;
            }
            set
            {
                this._Per_Personal_Id_Modifica = value;
            }
        }
        
        // Comentario
        public decimal Valor_Solicita
        {
            get
            {
                return this._Valor_Solicita;
            }
            set
            {
                this._Valor_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Planifica
        {
            get
            {
                return this._Per_Personal_Id_Planifica;
            }
            set
            {
                this._Per_Personal_Id_Planifica = value;
            }
        }
        
        // Comentario
        public string Esta_Planificada
        {
            get
            {
                return this._Esta_Planificada;
            }
            set
            {
                this._Esta_Planificada = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Contrata
        {
            get
            {
                return this._Per_Personal_Id_Contrata;
            }
            set
            {
                this._Per_Personal_Id_Contrata = value;
            }
        }
        
        // Comentario
        public string Esta_Contratada
        {
            get
            {
                return this._Esta_Contratada;
            }
            set
            {
                this._Esta_Contratada = value;
            }
        }
        
        // Comentario
        public string PAC_Linea
        {
            get
            {
                return this._PAC_Linea;
            }
            set
            {
                this._PAC_Linea = value;
            }
        }
        
        // Comentario
        public string CPC_Codigo
        {
            get
            {
                return this._CPC_Codigo;
            }
            set
            {
                this._CPC_Codigo = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Contrata
        {
            get
            {
                return this._Fecha_Contrata;
            }
            set
            {
                this._Fecha_Contrata = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Planifica
        {
            get
            {
                return this._Fecha_Planifica;
            }
            set
            {
                this._Fecha_Planifica = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Solicita
        {
            get
            {
                return this._Per_Personal_Nombre_Solicita;
            }
            set
            {
                this._Per_Personal_Nombre_Solicita = value;
            }
        }
        
        // Comentario
        public string Area_Nombre_Solicita
        {
            get
            {
                return this._Area_Nombre_Solicita;
            }
            set
            {
                this._Area_Nombre_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Crea
        {
            get
            {
                return this._Per_Personal_Nombre_Crea;
            }
            set
            {
                this._Per_Personal_Nombre_Crea = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Modifica
        {
            get
            {
                return this._Per_Personal_Nombre_Modifica;
            }
            set
            {
                this._Per_Personal_Nombre_Modifica = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Planifica
        {
            get
            {
                return this._Per_Personal_Nombre_Planifica;
            }
            set
            {
                this._Per_Personal_Nombre_Planifica = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Contrata
        {
            get
            {
                return this._Per_Personal_Nombre_Contrata;
            }
            set
            {
                this._Per_Personal_Nombre_Contrata = value;
            }
        }
        
        // Comentario
        public decimal Valor_Suma_Movs
        {
            get
            {
                return this._Valor_Suma_Movs;
            }
            set
            {
                this._Valor_Suma_Movs = value;
            }
        }
    }
}
