CREATE UNIQUE NONCLUSTERED INDEX [pbcatcol_idx]
    ON [dbo].[pbcatcol]([pbc_tnam] ASC, [pbc_ownr] ASC, [pbc_cnam] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

