CREATE NONCLUSTERED INDEX [RLSH_2_FK1]
    ON [dbo].[GDSEGTRA_HISTO]([GD_NUMERO] ASC, [GD_PERIODO] ASC, [GD_AREA_RESPONSABLE] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

