CREATE NONCLUSTERED INDEX [IX_Ver_Doc_Estado]
    ON [dbo].[Ver_Doc_Estado]([Apr_Doc_Estado_Id] ASC, [Ver_Version_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

