CREATE NONCLUSTERED INDEX [IX_Ver_Documento_Documento_Version]
    ON [dbo].[Ver_Documento]([Apr_Documento_Id] ASC, [Ver_Version_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

