ALTER TABLE [dbo].[Apu_Proyecto_Categoria]
    ADD CONSTRAINT [IX_Apu_Proyecto_Categoria_ProyCat] UNIQUE NONCLUSTERED ([Apu_Proyecto_Id] ASC, [Apu_Categoria_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

