ALTER TABLE [dbo].[Apu_Oferta_Equipo]
    ADD CONSTRAINT [IX_Apu_Oferta_Equipo_Oferta_Equipo] UNIQUE NONCLUSTERED ([Apu_Equipo_Id] ASC, [Apu_Oferta_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

