ALTER TABLE [dbo].[Apu_Material]
    ADD CONSTRAINT [IX_Apu_Material_Sucursal_Id_Nombre] UNIQUE NONCLUSTERED ([Nombre] ASC, [Int_Sucursal_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

