ALTER TABLE [dbo].[Aud_Par_Log]
    ADD CONSTRAINT [IX_Aud_Par_Log_Contenedor_Sucursal] UNIQUE NONCLUSTERED ([Dic_Contenedor_Id] ASC, [Int_Sucursal_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

