ALTER TABLE [dbo].[Dic_Dominio]
    ADD CONSTRAINT [IX_Dic_Dominio_Dic_Campo_Dominio] UNIQUE NONCLUSTERED ([Dic_Campo_Id] ASC, [Dominio] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

