ALTER TABLE [dbo].[Fis_Catalogo_Indice]
    ADD CONSTRAINT [IX_Fis_Catalogo_Indice_Catalogo_Indice] UNIQUE NONCLUSTERED ([Fis_Catalogo_Id] ASC, [Apu_Indice_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

