ALTER TABLE [dbo].[Par_Filtro]
    ADD CONSTRAINT [IX_Par_filtro_Usuario_Campo] UNIQUE NONCLUSTERED ([int_usuario_id] ASC, [dic_con_campo_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

