ALTER TABLE [dbo].[Ver_Mensaje]
    ADD CONSTRAINT [IX_Ver_Mensaje_Version_Mensaje] UNIQUE NONCLUSTERED ([Ver_Version_Id] ASC, [Par_Mensaje_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

