ALTER TABLE [dbo].[Apu_Rubro_Tecnica]
    ADD CONSTRAINT [PK_Apu_Rubro_Tecnica] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

