ALTER TABLE [dbo].[Apu_Proyecto_Mano_Obra]
    ADD CONSTRAINT [PK_Apu_Proyecto_Mano_Obra] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

