ALTER TABLE [dbo].[Dic_Con_Campo]
    ADD CONSTRAINT [PK_Dic_Con_Campo] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

