ALTER TABLE [dbo].[Fis_Catalogo_Indice]
    ADD CONSTRAINT [PK_Fis_Catalogo_Indice] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

