//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
     
    
    public class Com_Contrato_Tipo_Marca
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private int _Com_Contrato_Tipo_Id;
        
        // Comentario
        private string _Origen;
        
        // Comentario
        private string _Descripcion;
        
        // Comentario
        private string _Com_Contrato_Tipo_Nombre;
        
        public Com_Contrato_Tipo_Marca()
        {
        }
        
        public Com_Contrato_Tipo_Marca(int id, string nombre, int com_Contrato_Tipo_Id, string origen, string descripcion, string com_Contrato_Tipo_Nombre)
        {
            this.Id = id;
            this.Nombre = nombre;
            this.Com_Contrato_Tipo_Id = com_Contrato_Tipo_Id;
            this.Origen = origen;
            this.Descripcion = descripcion;
            this.Com_Contrato_Tipo_Nombre = com_Contrato_Tipo_Nombre;
        }
        
        public Com_Contrato_Tipo_Marca(Com_Contrato_Tipo_Marca o)
        {
            this.Id = o.Id;
            this.Nombre = o.Nombre;
            this.Com_Contrato_Tipo_Id = o.Com_Contrato_Tipo_Id;
            this.Origen = o.Origen;
            this.Descripcion = o.Descripcion;
            this.Com_Contrato_Tipo_Nombre = o.Com_Contrato_Tipo_Nombre;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public int Com_Contrato_Tipo_Id
        {
            get
            {
                return this._Com_Contrato_Tipo_Id;
            }
            set
            {
                this._Com_Contrato_Tipo_Id = value;
            }
        }
        
        // Comentario
        public string Origen
        {
            get
            {
                return this._Origen;
            }
            set
            {
                this._Origen = value;
            }
        }
        
        // Comentario
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }
        
        // Comentario
        public string Com_Contrato_Tipo_Nombre
        {
            get
            {
                return this._Com_Contrato_Tipo_Nombre;
            }
            set
            {
                this._Com_Contrato_Tipo_Nombre = value;
            }
        }
    }
}
