//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato_DocTec
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private int _Com_Contrato_Id;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private string _Tiene;
        
        public Com_Contrato_DocTec()
        {
        }
        
        public Com_Contrato_DocTec(int id, int com_Contrato_Id, string nombre, string tiene)
        {
            this.Id = id;
            this.Com_Contrato_Id = com_Contrato_Id;
            this.Nombre = nombre;
            this.Tiene = tiene;
        }
        
        public Com_Contrato_DocTec(Com_Contrato_DocTec o)
        {
            this.Id = o.Id;
            this.Com_Contrato_Id = o.Com_Contrato_Id;
            this.Nombre = o.Nombre;
            this.Tiene = o.Tiene;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public int Com_Contrato_Id
        {
            get
            {
                return this._Com_Contrato_Id;
            }
            set
            {
                this._Com_Contrato_Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public string Tiene
        {
            get
            {
                return this._Tiene;
            }
            set
            {
                this._Tiene = value;
            }
        }
    }
}
