//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
  
namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
     
    
    public class Com_DocTec
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Nombre;
        
        public Com_DocTec()
        {
        }
        
        public Com_DocTec(int id, string nombre)
        {
            this.Id = id;
            this.Nombre = nombre;
        }
        
        public Com_DocTec(Com_DocTec o)
        {
            this.Id = o.Id;
            this.Nombre = o.Nombre;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
    }
}
