//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private int _Pla_Doc_Id;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private int _Com_Procedimiento_Id;
        
        // Comentario
        private decimal _Porcentaje_Anticipo_Ref;
        
        // Comentario
        private int _Plazo_Ref;
        
        // Comentario
        private string _Codigo_Sercop;
        
        // Comentario
        private string _Per_Personal_Resp_Exp;
        
        // Comentario
        private System.DateTime _Fecha_Cierre_Rec_Ofertas;
        
        // Comentario
        private string _Par_Razon_Social_Id_Contratista;
        
        // Comentario
        private decimal _Valor_Contrato;
        
        // Comentario
        private int _Plazo_Contrato;
        
        // Comentario
        private System.DateTime _Fecha_Inicio_Contrato;
        
        // Comentario
        private decimal _Porcentaje_Anticipo_Contrato;
        
        // Comentario
        private string _Per_Personal_Id_Admin;
        
        // Comentario
        private string _Desc_Contrata;
        
        // Comentario
        private System.DateTime _Fecha_Crea;
        
        // Comentario
        private int _Pla_Tarea_Id;
        
        // Comentario
        private string _Pla_Tarea_Codigo;
        
        // Comentario
        private string _Pla_Tarea_Nombre;
        
        // Comentario
        private string _Per_Personal_Nombre_Admin;
        
        // Comentario
        private decimal _Valor_Suma_Movs;
        
        // Comentario
        private string _Com_Procedimiento_Tipo;
        
        // Comentario
        private string _Com_Procedimiento_Nombre;
        
        // Comentario
        private string _Per_Personal_Nombre_Resp_Exp;
        
        // Comentario
        private string _Per_Personal_Id_Solicita;
        
        // Comentario
        private string _Per_Personal_Nombre_Solicita;
        
        // Comentario
        private string _Par_Razon_Social_Nombre_Contratista;
        
        // Comentario
        private string _Par_Razon_Social_Numero_Contratista;
        
        // Comentario
        private string _Pla_Doc_Cedula_Presup_Codigo;
        
        // Comentario
        private string _Pla_Doc_CPC_Codigo;
        
        // Comentario
        private string _Pla_Doc_PAC_Linea;
        
        // Comentario
        private string _Pla_Doc_Codigo;
        
        // Comentario
        private int _Pla_Cta_Id;
        
        // Comentario
        private string _Pla_Cta_Codigo;
        
        // Comentario
        private string _Pla_Cta_Nombre;
        
        // Comentario
        private decimal _Pla_Doc_Valor_Solicita;
        
        // Comentario
        private string _Com_Procedimiento_Desc;
        
        // Comentario
        private string _Estado_Portal;
        
        // Comentario
        private string _Estado_Contratacion;
        
        // Comentario
        private System.DateTime _Fecha_Inicio_Elabora_Pliegos;
        
        // Comentario
        private System.DateTime _Fecha_Publicacion_Portal;
        
        // Comentario
        private System.DateTime _Fecha_Calificaciones;
        
        // Comentario
        private System.DateTime _Fecha_Estimada_Adjudicacion;
        
        // Comentario
        private System.DateTime _Fecha_Adjudicacion;
        
        // Comentario
        private System.DateTime _Fecha_Juridico;
        
        public Com_Contrato()
        {
        }
        
        public Com_Contrato(
                    int id, 
                    int pla_Doc_Id, 
                    string estado, 
                    int com_Procedimiento_Id, 
                    decimal porcentaje_Anticipo_Ref, 
                    int plazo_Ref, 
                    string codigo_Sercop, 
                    string per_Personal_Resp_Exp, 
                    System.DateTime fecha_Cierre_Rec_Ofertas, 
                    string par_Razon_Social_Id_Contratista, 
                    decimal valor_Contrato, 
                    int plazo_Contrato, 
                    System.DateTime fecha_Inicio_Contrato, 
                    decimal porcentaje_Anticipo_Contrato, 
                    string per_Personal_Id_Admin, 
                    string desc_Contrata, 
                    System.DateTime fecha_Crea, 
                    int pla_Tarea_Id, 
                    string pla_Tarea_Codigo, 
                    string pla_Tarea_Nombre, 
                    string per_Personal_Nombre_Admin, 
                    decimal valor_Suma_Movs, 
                    string com_Procedimiento_Tipo, 
                    string com_Procedimiento_Nombre, 
                    string per_Personal_Nombre_Resp_Exp, 
                    string per_Personal_Id_Solicita, 
                    string per_Personal_Nombre_Solicita, 
                    string par_Razon_Social_Nombre_Contratista, 
                    string par_Razon_Social_Numero_Contratista, 
                    string pla_Doc_Cedula_Presup_Codigo, 
                    string pla_Doc_CPC_Codigo, 
                    string pla_Doc_PAC_Linea, 
                    string pla_Doc_Codigo, 
                    int pla_Cta_Id, 
                    string pla_Cta_Codigo, 
                    string pla_Cta_Nombre, 
                    decimal pla_Doc_Valor_Solicita, 
                    string com_Procedimiento_Desc, 
                    string estado_Portal, 
                    string estado_Contratacion, 
                    System.DateTime fecha_Inicio_Elabora_Pliegos, 
                    System.DateTime fecha_Publicacion_Portal, 
                    System.DateTime fecha_Calificaciones, 
                    System.DateTime fecha_Estimada_Adjudicacion, 
                    System.DateTime fecha_Adjudicacion, 
                    System.DateTime fecha_Juridico)
        {
            this.Id = id;
            this.Pla_Doc_Id = pla_Doc_Id;
            this.Estado = estado;
            this.Com_Procedimiento_Id = com_Procedimiento_Id;
            this.Porcentaje_Anticipo_Ref = porcentaje_Anticipo_Ref;
            this.Plazo_Ref = plazo_Ref;
            this.Codigo_Sercop = codigo_Sercop;
            this.Per_Personal_Resp_Exp = per_Personal_Resp_Exp;
            this.Fecha_Cierre_Rec_Ofertas = fecha_Cierre_Rec_Ofertas;
            this.Par_Razon_Social_Id_Contratista = par_Razon_Social_Id_Contratista;
            this.Valor_Contrato = valor_Contrato;
            this.Plazo_Contrato = plazo_Contrato;
            this.Fecha_Inicio_Contrato = fecha_Inicio_Contrato;
            this.Porcentaje_Anticipo_Contrato = porcentaje_Anticipo_Contrato;
            this.Per_Personal_Id_Admin = per_Personal_Id_Admin;
            this.Desc_Contrata = desc_Contrata;
            this.Fecha_Crea = fecha_Crea;
            this.Pla_Tarea_Id = pla_Tarea_Id;
            this.Pla_Tarea_Codigo = pla_Tarea_Codigo;
            this.Pla_Tarea_Nombre = pla_Tarea_Nombre;
            this.Per_Personal_Nombre_Admin = per_Personal_Nombre_Admin;
            this.Valor_Suma_Movs = valor_Suma_Movs;
            this.Com_Procedimiento_Tipo = com_Procedimiento_Tipo;
            this.Com_Procedimiento_Nombre = com_Procedimiento_Nombre;
            this.Per_Personal_Nombre_Resp_Exp = per_Personal_Nombre_Resp_Exp;
            this.Per_Personal_Id_Solicita = per_Personal_Id_Solicita;
            this.Per_Personal_Nombre_Solicita = per_Personal_Nombre_Solicita;
            this.Par_Razon_Social_Nombre_Contratista = par_Razon_Social_Nombre_Contratista;
            this.Par_Razon_Social_Numero_Contratista = par_Razon_Social_Numero_Contratista;
            this.Pla_Doc_Cedula_Presup_Codigo = pla_Doc_Cedula_Presup_Codigo;
            this.Pla_Doc_CPC_Codigo = pla_Doc_CPC_Codigo;
            this.Pla_Doc_PAC_Linea = pla_Doc_PAC_Linea;
            this.Pla_Doc_Codigo = pla_Doc_Codigo;
            this.Pla_Cta_Id = pla_Cta_Id;
            this.Pla_Cta_Codigo = pla_Cta_Codigo;
            this.Pla_Cta_Nombre = pla_Cta_Nombre;
            this.Pla_Doc_Valor_Solicita = pla_Doc_Valor_Solicita;
            this.Com_Procedimiento_Desc = com_Procedimiento_Desc;
            this.Estado_Portal = estado_Portal;
            this.Estado_Contratacion = estado_Contratacion;
            this.Fecha_Inicio_Elabora_Pliegos = fecha_Inicio_Elabora_Pliegos;
            this.Fecha_Publicacion_Portal = fecha_Publicacion_Portal;
            this.Fecha_Calificaciones = fecha_Calificaciones;
            this.Fecha_Estimada_Adjudicacion = fecha_Estimada_Adjudicacion;
            this.Fecha_Adjudicacion = fecha_Adjudicacion;
            this.Fecha_Juridico = fecha_Juridico;
        }
        
        public Com_Contrato(Com_Contrato o)
        {
            this.Id = o.Id;
            this.Pla_Doc_Id = o.Pla_Doc_Id;
            this.Estado = o.Estado;
            this.Com_Procedimiento_Id = o.Com_Procedimiento_Id;
            this.Porcentaje_Anticipo_Ref = o.Porcentaje_Anticipo_Ref;
            this.Plazo_Ref = o.Plazo_Ref;
            this.Codigo_Sercop = o.Codigo_Sercop;
            this.Per_Personal_Resp_Exp = o.Per_Personal_Resp_Exp;
            this.Fecha_Cierre_Rec_Ofertas = o.Fecha_Cierre_Rec_Ofertas;
            this.Par_Razon_Social_Id_Contratista = o.Par_Razon_Social_Id_Contratista;
            this.Valor_Contrato = o.Valor_Contrato;
            this.Plazo_Contrato = o.Plazo_Contrato;
            this.Fecha_Inicio_Contrato = o.Fecha_Inicio_Contrato;
            this.Porcentaje_Anticipo_Contrato = o.Porcentaje_Anticipo_Contrato;
            this.Per_Personal_Id_Admin = o.Per_Personal_Id_Admin;
            this.Desc_Contrata = o.Desc_Contrata;
            this.Fecha_Crea = o.Fecha_Crea;
            this.Pla_Tarea_Id = o.Pla_Tarea_Id;
            this.Pla_Tarea_Codigo = o.Pla_Tarea_Codigo;
            this.Pla_Tarea_Nombre = o.Pla_Tarea_Nombre;
            this.Per_Personal_Nombre_Admin = o.Per_Personal_Nombre_Admin;
            this.Valor_Suma_Movs = o.Valor_Suma_Movs;
            this.Com_Procedimiento_Tipo = o.Com_Procedimiento_Tipo;
            this.Com_Procedimiento_Nombre = o.Com_Procedimiento_Nombre;
            this.Per_Personal_Nombre_Resp_Exp = o.Per_Personal_Nombre_Resp_Exp;
            this.Per_Personal_Id_Solicita = o.Per_Personal_Id_Solicita;
            this.Per_Personal_Nombre_Solicita = o.Per_Personal_Nombre_Solicita;
            this.Par_Razon_Social_Nombre_Contratista = o.Par_Razon_Social_Nombre_Contratista;
            this.Par_Razon_Social_Numero_Contratista = o.Par_Razon_Social_Numero_Contratista;
            this.Pla_Doc_Cedula_Presup_Codigo = o.Pla_Doc_Cedula_Presup_Codigo;
            this.Pla_Doc_CPC_Codigo = o.Pla_Doc_CPC_Codigo;
            this.Pla_Doc_PAC_Linea = o.Pla_Doc_PAC_Linea;
            this.Pla_Doc_Codigo = o.Pla_Doc_Codigo;
            this.Pla_Cta_Id = o.Pla_Cta_Id;
            this.Pla_Cta_Codigo = o.Pla_Cta_Codigo;
            this.Pla_Cta_Nombre = o.Pla_Cta_Nombre;
            this.Pla_Doc_Valor_Solicita = o.Pla_Doc_Valor_Solicita;
            this.Com_Procedimiento_Desc = o.Com_Procedimiento_Desc;
            this.Estado_Portal = o.Estado_Portal;
            this.Estado_Contratacion = o.Estado_Contratacion;
            this.Fecha_Inicio_Elabora_Pliegos = o.Fecha_Inicio_Elabora_Pliegos;
            this.Fecha_Publicacion_Portal = o.Fecha_Publicacion_Portal;
            this.Fecha_Calificaciones = o.Fecha_Calificaciones;
            this.Fecha_Estimada_Adjudicacion = o.Fecha_Estimada_Adjudicacion;
            this.Fecha_Adjudicacion = o.Fecha_Adjudicacion;
            this.Fecha_Juridico = o.Fecha_Juridico;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public int Pla_Doc_Id
        {
            get
            {
                return this._Pla_Doc_Id;
            }
            set
            {
                this._Pla_Doc_Id = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public int Com_Procedimiento_Id
        {
            get
            {
                return this._Com_Procedimiento_Id;
            }
            set
            {
                this._Com_Procedimiento_Id = value;
            }
        }
        
        // Comentario
        public decimal Porcentaje_Anticipo_Ref
        {
            get
            {
                return this._Porcentaje_Anticipo_Ref;
            }
            set
            {
                this._Porcentaje_Anticipo_Ref = value;
            }
        }
        
        // Comentario
        public int Plazo_Ref
        {
            get
            {
                return this._Plazo_Ref;
            }
            set
            {
                this._Plazo_Ref = value;
            }
        }
        
        // Comentario
        public string Codigo_Sercop
        {
            get
            {
                return this._Codigo_Sercop;
            }
            set
            {
                this._Codigo_Sercop = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Resp_Exp
        {
            get
            {
                return this._Per_Personal_Resp_Exp;
            }
            set
            {
                this._Per_Personal_Resp_Exp = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Cierre_Rec_Ofertas
        {
            get
            {
                return this._Fecha_Cierre_Rec_Ofertas;
            }
            set
            {
                this._Fecha_Cierre_Rec_Ofertas = value;
            }
        }
        
        // Comentario
        public string Par_Razon_Social_Id_Contratista
        {
            get
            {
                return this._Par_Razon_Social_Id_Contratista;
            }
            set
            {
                this._Par_Razon_Social_Id_Contratista = value;
            }
        }
        
        // Comentario
        public decimal Valor_Contrato
        {
            get
            {
                return this._Valor_Contrato;
            }
            set
            {
                this._Valor_Contrato = value;
            }
        }
        
        // Comentario
        public int Plazo_Contrato
        {
            get
            {
                return this._Plazo_Contrato;
            }
            set
            {
                this._Plazo_Contrato = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Inicio_Contrato
        {
            get
            {
                return this._Fecha_Inicio_Contrato;
            }
            set
            {
                this._Fecha_Inicio_Contrato = value;
            }
        }
        
        // Comentario
        public decimal Porcentaje_Anticipo_Contrato
        {
            get
            {
                return this._Porcentaje_Anticipo_Contrato;
            }
            set
            {
                this._Porcentaje_Anticipo_Contrato = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Admin
        {
            get
            {
                return this._Per_Personal_Id_Admin;
            }
            set
            {
                this._Per_Personal_Id_Admin = value;
            }
        }
        
        // Comentario
        public string Desc_Contrata
        {
            get
            {
                return this._Desc_Contrata;
            }
            set
            {
                this._Desc_Contrata = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Crea
        {
            get
            {
                return this._Fecha_Crea;
            }
            set
            {
                this._Fecha_Crea = value;
            }
        }
        
        // Comentario
        public int Pla_Tarea_Id
        {
            get
            {
                return this._Pla_Tarea_Id;
            }
            set
            {
                this._Pla_Tarea_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Codigo
        {
            get
            {
                return this._Pla_Tarea_Codigo;
            }
            set
            {
                this._Pla_Tarea_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Nombre
        {
            get
            {
                return this._Pla_Tarea_Nombre;
            }
            set
            {
                this._Pla_Tarea_Nombre = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Admin
        {
            get
            {
                return this._Per_Personal_Nombre_Admin;
            }
            set
            {
                this._Per_Personal_Nombre_Admin = value;
            }
        }
        
        // Comentario
        public decimal Valor_Suma_Movs
        {
            get
            {
                return this._Valor_Suma_Movs;
            }
            set
            {
                this._Valor_Suma_Movs = value;
            }
        }
        
        // Comentario
        public string Com_Procedimiento_Tipo
        {
            get
            {
                return this._Com_Procedimiento_Tipo;
            }
            set
            {
                this._Com_Procedimiento_Tipo = value;
            }
        }
        
        // Comentario
        public string Com_Procedimiento_Nombre
        {
            get
            {
                return this._Com_Procedimiento_Nombre;
            }
            set
            {
                this._Com_Procedimiento_Nombre = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Resp_Exp
        {
            get
            {
                return this._Per_Personal_Nombre_Resp_Exp;
            }
            set
            {
                this._Per_Personal_Nombre_Resp_Exp = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id_Solicita
        {
            get
            {
                return this._Per_Personal_Id_Solicita;
            }
            set
            {
                this._Per_Personal_Id_Solicita = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre_Solicita
        {
            get
            {
                return this._Per_Personal_Nombre_Solicita;
            }
            set
            {
                this._Per_Personal_Nombre_Solicita = value;
            }
        }
        
        // Comentario
        public string Par_Razon_Social_Nombre_Contratista
        {
            get
            {
                return this._Par_Razon_Social_Nombre_Contratista;
            }
            set
            {
                this._Par_Razon_Social_Nombre_Contratista = value;
            }
        }
        
        // Comentario
        public string Par_Razon_Social_Numero_Contratista
        {
            get
            {
                return this._Par_Razon_Social_Numero_Contratista;
            }
            set
            {
                this._Par_Razon_Social_Numero_Contratista = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_Cedula_Presup_Codigo
        {
            get
            {
                return this._Pla_Doc_Cedula_Presup_Codigo;
            }
            set
            {
                this._Pla_Doc_Cedula_Presup_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_CPC_Codigo
        {
            get
            {
                return this._Pla_Doc_CPC_Codigo;
            }
            set
            {
                this._Pla_Doc_CPC_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_PAC_Linea
        {
            get
            {
                return this._Pla_Doc_PAC_Linea;
            }
            set
            {
                this._Pla_Doc_PAC_Linea = value;
            }
        }
        
        // Comentario
        public string Pla_Doc_Codigo
        {
            get
            {
                return this._Pla_Doc_Codigo;
            }
            set
            {
                this._Pla_Doc_Codigo = value;
            }
        }
        
        // Comentario
        public int Pla_Cta_Id
        {
            get
            {
                return this._Pla_Cta_Id;
            }
            set
            {
                this._Pla_Cta_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Codigo
        {
            get
            {
                return this._Pla_Cta_Codigo;
            }
            set
            {
                this._Pla_Cta_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Nombre
        {
            get
            {
                return this._Pla_Cta_Nombre;
            }
            set
            {
                this._Pla_Cta_Nombre = value;
            }
        }
        
        // Comentario
        public decimal Pla_Doc_Valor_Solicita
        {
            get
            {
                return this._Pla_Doc_Valor_Solicita;
            }
            set
            {
                this._Pla_Doc_Valor_Solicita = value;
            }
        }
        
        // Comentario
        public string Com_Procedimiento_Desc
        {
            get
            {
                return this._Com_Procedimiento_Desc;
            }
            set
            {
                this._Com_Procedimiento_Desc = value;
            }
        }
        
        // Comentario
        public string Estado_Portal
        {
            get
            {
                return this._Estado_Portal;
            }
            set
            {
                this._Estado_Portal = value;
            }
        }
        
        // Comentario
        public string Estado_Contratacion
        {
            get
            {
                return this._Estado_Contratacion;
            }
            set
            {
                this._Estado_Contratacion = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Inicio_Elabora_Pliegos
        {
            get
            {
                return this._Fecha_Inicio_Elabora_Pliegos;
            }
            set
            {
                this._Fecha_Inicio_Elabora_Pliegos = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Publicacion_Portal
        {
            get
            {
                return this._Fecha_Publicacion_Portal;
            }
            set
            {
                this._Fecha_Publicacion_Portal = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Calificaciones
        {
            get
            {
                return this._Fecha_Calificaciones;
            }
            set
            {
                this._Fecha_Calificaciones = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Estimada_Adjudicacion
        {
            get
            {
                return this._Fecha_Estimada_Adjudicacion;
            }
            set
            {
                this._Fecha_Estimada_Adjudicacion = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Adjudicacion
        {
            get
            {
                return this._Fecha_Adjudicacion;
            }
            set
            {
                this._Fecha_Adjudicacion = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Juridico
        {
            get
            {
                return this._Fecha_Juridico;
            }
            set
            {
                this._Fecha_Juridico = value;
            }
        }
    }
}
