//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Contrato_Legal
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private int _Com_Contrato_Id;
        
        // Comentario
        private int _Com_Contrato_Tipo_Id;
        
        // Comentario
        private string _URL_Contrato_Word;
        
        // Comentario
        private string _URL_Contrato_Scan;
        
        // Comentario
        private string _Desc_Alerta_1;
        
        // Comentario
        private string _Desc_Alerta_2;
        
        // Comentario
        private string _Desc_Alerta_3;
        
        // Comentario
        private System.DateTime _Fecha_Firma_Contrato;
        
        // Comentario
        private System.DateTime _Fecha_Contrato;
        
        // Comentario
        private string _Com_Contrato_Tipo_Nombre;
        
        public Com_Contrato_Legal()
        {
        }
        
        public Com_Contrato_Legal(int id, int com_Contrato_Id, int com_Contrato_Tipo_Id, string uRL_Contrato_Word, string uRL_Contrato_Scan, string desc_Alerta_1, string desc_Alerta_2, string desc_Alerta_3, System.DateTime fecha_Firma_Contrato, System.DateTime fecha_Contrato, string com_Contrato_Tipo_Nombre)
        {
            this.Id = id;
            this.Com_Contrato_Id = com_Contrato_Id;
            this.Com_Contrato_Tipo_Id = com_Contrato_Tipo_Id;
            this.URL_Contrato_Word = uRL_Contrato_Word;
            this.URL_Contrato_Scan = uRL_Contrato_Scan;
            this.Desc_Alerta_1 = desc_Alerta_1;
            this.Desc_Alerta_2 = desc_Alerta_2;
            this.Desc_Alerta_3 = desc_Alerta_3;
            this.Fecha_Firma_Contrato = fecha_Firma_Contrato;
            this.Fecha_Contrato = fecha_Contrato;
            this.Com_Contrato_Tipo_Nombre = com_Contrato_Tipo_Nombre;
        }
        
        public Com_Contrato_Legal(Com_Contrato_Legal o)
        {
            this.Id = o.Id;
            this.Com_Contrato_Id = o.Com_Contrato_Id;
            this.Com_Contrato_Tipo_Id = o.Com_Contrato_Tipo_Id;
            this.URL_Contrato_Word = o.URL_Contrato_Word;
            this.URL_Contrato_Scan = o.URL_Contrato_Scan;
            this.Desc_Alerta_1 = o.Desc_Alerta_1;
            this.Desc_Alerta_2 = o.Desc_Alerta_2;
            this.Desc_Alerta_3 = o.Desc_Alerta_3;
            this.Fecha_Firma_Contrato = o.Fecha_Firma_Contrato;
            this.Fecha_Contrato = o.Fecha_Contrato;
            this.Com_Contrato_Tipo_Nombre = o.Com_Contrato_Tipo_Nombre;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public int Com_Contrato_Id
        {
            get
            {
                return this._Com_Contrato_Id;
            }
            set
            {
                this._Com_Contrato_Id = value;
            }
        }
        
        // Comentario
        public int Com_Contrato_Tipo_Id
        {
            get
            {
                return this._Com_Contrato_Tipo_Id;
            }
            set
            {
                this._Com_Contrato_Tipo_Id = value;
            }
        }
        
        // Comentario
        public string URL_Contrato_Word
        {
            get
            {
                return this._URL_Contrato_Word;
            }
            set
            {
                this._URL_Contrato_Word = value;
            }
        }
        
        // Comentario
        public string URL_Contrato_Scan
        {
            get
            {
                return this._URL_Contrato_Scan;
            }
            set
            {
                this._URL_Contrato_Scan = value;
            }
        }
        
        // Comentario
        public string Desc_Alerta_1
        {
            get
            {
                return this._Desc_Alerta_1;
            }
            set
            {
                this._Desc_Alerta_1 = value;
            }
        }
        
        // Comentario
        public string Desc_Alerta_2
        {
            get
            {
                return this._Desc_Alerta_2;
            }
            set
            {
                this._Desc_Alerta_2 = value;
            }
        }
        
        // Comentario
        public string Desc_Alerta_3
        {
            get
            {
                return this._Desc_Alerta_3;
            }
            set
            {
                this._Desc_Alerta_3 = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Firma_Contrato
        {
            get
            {
                return this._Fecha_Firma_Contrato;
            }
            set
            {
                this._Fecha_Firma_Contrato = value;
            }
        }
        
        // Comentario
        public System.DateTime Fecha_Contrato
        {
            get
            {
                return this._Fecha_Contrato;
            }
            set
            {
                this._Fecha_Contrato = value;
            }
        }
        
        // Comentario
        public string Com_Contrato_Tipo_Nombre
        {
            get
            {
                return this._Com_Contrato_Tipo_Nombre;
            }
            set
            {
                this._Com_Contrato_Tipo_Nombre = value;
            }
        }
    }
}
