//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.COM
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Com_Procedimiento
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private string _Tipo;
        
        // Comentario
        private decimal _Valor_Min;
        
        // Comentario
        private decimal _Valor_Max;
        
        public Com_Procedimiento()
        {
        }
        
        public Com_Procedimiento(int id, string nombre, string tipo, decimal valor_Min, decimal valor_Max)
        {
            this.Id = id;
            this.Nombre = nombre;
            this.Tipo = tipo;
            this.Valor_Min = valor_Min;
            this.Valor_Max = valor_Max;
        }
        
        public Com_Procedimiento(Com_Procedimiento o)
        {
            this.Id = o.Id;
            this.Nombre = o.Nombre;
            this.Tipo = o.Tipo;
            this.Valor_Min = o.Valor_Min;
            this.Valor_Max = o.Valor_Max;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public string Tipo
        {
            get
            {
                return this._Tipo;
            }
            set
            {
                this._Tipo = value;
            }
        }
        
        // Comentario
        public decimal Valor_Min
        {
            get
            {
                return this._Valor_Min;
            }
            set
            {
                this._Valor_Min = value;
            }
        }
        
        // Comentario
        public decimal Valor_Max
        {
            get
            {
                return this._Valor_Max;
            }
            set
            {
                this._Valor_Max = value;
            }
        }
    }
}
