//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Lote_Tipo
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private string _Nombre;
        
        // Comentario
        private string _Archivo_Tipo;
        
        // Comentario
        private string _Clase;
        
        // Comentario
        private string _Metodo;
        
        public Pla_Lote_Tipo()
        {
        }
        
        public Pla_Lote_Tipo(int id, string codigo, string nombre, string archivo_Tipo, string clase, string metodo)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Nombre = nombre;
            this.Archivo_Tipo = archivo_Tipo;
            this.Clase = clase;
            this.Metodo = metodo;
        }
        
        public Pla_Lote_Tipo(Pla_Lote_Tipo o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Nombre = o.Nombre;
            this.Archivo_Tipo = o.Archivo_Tipo;
            this.Clase = o.Clase;
            this.Metodo = o.Metodo;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this._Nombre = value;
            }
        }
        
        // Comentario
        public string Archivo_Tipo
        {
            get
            {
                return this._Archivo_Tipo;
            }
            set
            {
                this._Archivo_Tipo = value;
            }
        }
        
        // Comentario
        public string Clase
        {
            get
            {
                return this._Clase;
            }
            set
            {
                this._Clase = value;
            }
        }
        
        // Comentario
        public string Metodo
        {
            get
            {
                return this._Metodo;
            }
            set
            {
                this._Metodo = value;
            }
        }
    }
}
