//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
 
namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_PersonalDatos
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Per_Personal_Id;
        
        // Comentario
        private string _Pie_Firma_Nombre;
        
        // Comentario
        private string _Pie_Firma_Cargo;
        
        // Comentario
        private string _Email_Inst;
        
        // Comentario
        private string _Per_Personal_Nombre;
        
        // Comentario
        private string _Per_Personal_NumeroDoc;
        
        public Pla_PersonalDatos()
        {
        }
        
        public Pla_PersonalDatos(int id, string per_Personal_Id, string pie_Firma_Nombre, string pie_Firma_Cargo, string email_Inst, string per_Personal_Nombre, string per_Personal_NumeroDoc)
        {
            this.Id = id;
            this.Per_Personal_Id = per_Personal_Id;
            this.Pie_Firma_Nombre = pie_Firma_Nombre;
            this.Pie_Firma_Cargo = pie_Firma_Cargo;
            this.Email_Inst = email_Inst;
            this.Per_Personal_Nombre = per_Personal_Nombre;
            this.Per_Personal_NumeroDoc = per_Personal_NumeroDoc;
        }
        
        public Pla_PersonalDatos(Pla_PersonalDatos o)
        {
            this.Id = o.Id;
            this.Per_Personal_Id = o.Per_Personal_Id;
            this.Pie_Firma_Nombre = o.Pie_Firma_Nombre;
            this.Pie_Firma_Cargo = o.Pie_Firma_Cargo;
            this.Email_Inst = o.Email_Inst;
            this.Per_Personal_Nombre = o.Per_Personal_Nombre;
            this.Per_Personal_NumeroDoc = o.Per_Personal_NumeroDoc;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Id
        {
            get
            {
                return this._Per_Personal_Id;
            }
            set
            {
                this._Per_Personal_Id = value;
            }
        }
        
        // Comentario
        public string Pie_Firma_Nombre
        {
            get
            {
                return this._Pie_Firma_Nombre;
            }
            set
            {
                this._Pie_Firma_Nombre = value;
            }
        }
        
        // Comentario
        public string Pie_Firma_Cargo
        {
            get
            {
                return this._Pie_Firma_Cargo;
            }
            set
            {
                this._Pie_Firma_Cargo = value;
            }
        }
        
        // Comentario
        public string Email_Inst
        {
            get
            {
                return this._Email_Inst;
            }
            set
            {
                this._Email_Inst = value;
            }
        }
        
        // Comentario
        public string Per_Personal_Nombre
        {
            get
            {
                return this._Per_Personal_Nombre;
            }
            set
            {
                this._Per_Personal_Nombre = value;
            }
        }
        
        // Comentario
        public string Per_Personal_NumeroDoc
        {
            get
            {
                return this._Per_Personal_NumeroDoc;
            }
            set
            {
                this._Per_Personal_NumeroDoc = value;
            }
        }
    }
}
