//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEL.PLA
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    
    
    public class Pla_Poa
    {
        
        // Comentario
        private int _Id;
        
        // Comentario
        private string _Codigo;
        
        // Comentario
        private int _Pla_Tarea_Id;
        
        // Comentario
        private int _Pla_Partida_Id;
        
        // Comentario
        private string _Estado;
        
        // Comentario
        private string _Pla_Tarea_Codigo;
        
        // Comentario
        private string _Pla_Tarea_Nombre;
        
        // Comentario
        private int _Pla_Cta_Id;
        
        // Comentario
        private string _Pla_Cta_Codigo;
        
        // Comentario
        private string _Pla_Cta_Nombre;
        
        // Comentario
        private string _Pla_Partida_Codigo;
        
        // Comentario
        private string _Pla_Partida_Nombre;
        
        // Comentario
        private decimal _Valor_Inicial;
        
        // Comentario
        private decimal _Valor_Suma;
        
        public Pla_Poa()
        {
        }
        
        public Pla_Poa(int id, string codigo, int pla_Tarea_Id, int pla_Partida_Id, string estado, string pla_Tarea_Codigo, string pla_Tarea_Nombre, int pla_Cta_Id, string pla_Cta_Codigo, string pla_Cta_Nombre, string pla_Partida_Codigo, string pla_Partida_Nombre, decimal valor_Inicial, decimal valor_Suma)
        {
            this.Id = id;
            this.Codigo = codigo;
            this.Pla_Tarea_Id = pla_Tarea_Id;
            this.Pla_Partida_Id = pla_Partida_Id;
            this.Estado = estado;
            this.Pla_Tarea_Codigo = pla_Tarea_Codigo;
            this.Pla_Tarea_Nombre = pla_Tarea_Nombre;
            this.Pla_Cta_Id = pla_Cta_Id;
            this.Pla_Cta_Codigo = pla_Cta_Codigo;
            this.Pla_Cta_Nombre = pla_Cta_Nombre;
            this.Pla_Partida_Codigo = pla_Partida_Codigo;
            this.Pla_Partida_Nombre = pla_Partida_Nombre;
            this.Valor_Inicial = valor_Inicial;
            this.Valor_Suma = valor_Suma;
        }
        
        public Pla_Poa(Pla_Poa o)
        {
            this.Id = o.Id;
            this.Codigo = o.Codigo;
            this.Pla_Tarea_Id = o.Pla_Tarea_Id;
            this.Pla_Partida_Id = o.Pla_Partida_Id;
            this.Estado = o.Estado;
            this.Pla_Tarea_Codigo = o.Pla_Tarea_Codigo;
            this.Pla_Tarea_Nombre = o.Pla_Tarea_Nombre;
            this.Pla_Cta_Id = o.Pla_Cta_Id;
            this.Pla_Cta_Codigo = o.Pla_Cta_Codigo;
            this.Pla_Cta_Nombre = o.Pla_Cta_Nombre;
            this.Pla_Partida_Codigo = o.Pla_Partida_Codigo;
            this.Pla_Partida_Nombre = o.Pla_Partida_Nombre;
            this.Valor_Inicial = o.Valor_Inicial;
            this.Valor_Suma = o.Valor_Suma;
        }
        
        // Comentario
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }
        
        // Comentario
        public string Codigo
        {
            get
            {
                return this._Codigo;
            }
            set
            {
                this._Codigo = value;
            }
        }
        
        // Comentario
        public int Pla_Tarea_Id
        {
            get
            {
                return this._Pla_Tarea_Id;
            }
            set
            {
                this._Pla_Tarea_Id = value;
            }
        }
        
        // Comentario
        public int Pla_Partida_Id
        {
            get
            {
                return this._Pla_Partida_Id;
            }
            set
            {
                this._Pla_Partida_Id = value;
            }
        }
        
        // Comentario
        public string Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this._Estado = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Codigo
        {
            get
            {
                return this._Pla_Tarea_Codigo;
            }
            set
            {
                this._Pla_Tarea_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Tarea_Nombre
        {
            get
            {
                return this._Pla_Tarea_Nombre;
            }
            set
            {
                this._Pla_Tarea_Nombre = value;
            }
        }
        
        // Comentario
        public int Pla_Cta_Id
        {
            get
            {
                return this._Pla_Cta_Id;
            }
            set
            {
                this._Pla_Cta_Id = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Codigo
        {
            get
            {
                return this._Pla_Cta_Codigo;
            }
            set
            {
                this._Pla_Cta_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Cta_Nombre
        {
            get
            {
                return this._Pla_Cta_Nombre;
            }
            set
            {
                this._Pla_Cta_Nombre = value;
            }
        }
        
        // Comentario
        public string Pla_Partida_Codigo
        {
            get
            {
                return this._Pla_Partida_Codigo;
            }
            set
            {
                this._Pla_Partida_Codigo = value;
            }
        }
        
        // Comentario
        public string Pla_Partida_Nombre
        {
            get
            {
                return this._Pla_Partida_Nombre;
            }
            set
            {
                this._Pla_Partida_Nombre = value;
            }
        }
        
        // Comentario
        public decimal Valor_Inicial
        {
            get
            {
                return this._Valor_Inicial;
            }
            set
            {
                this._Valor_Inicial = value;
            }
        }
        
        // Comentario
        public decimal Valor_Suma
        {
            get
            {
                return this._Valor_Suma;
            }
            set
            {
                this._Valor_Suma = value;
            }
        }
    }
}
