ALTER TABLE [dbo].[Apu_Subtitulo]
    ADD CONSTRAINT [IX_Apu_Subtitulo_Nombre_Empresa] UNIQUE NONCLUSTERED ([Nombre] ASC, [Int_Empresa_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

