ALTER TABLE [dbo].[Dic_Campo]
    ADD CONSTRAINT [IX_Dic_Campo_Dic_Objeto_Nombre] UNIQUE NONCLUSTERED ([Dic_Objeto_Id] ASC, [Nombre] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

