ALTER TABLE [dbo].[Par_Servidor_Det]
    ADD CONSTRAINT [IX_Par_Servidor_Det] UNIQUE NONCLUSTERED ([Referencia] ASC, [Par_Servidor_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

