ALTER TABLE [dbo].[Par_Filtro]
    ADD CONSTRAINT [IX_Par_filtro_codigo] UNIQUE NONCLUSTERED ([codigo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

