ALTER TABLE [dbo].[Par_Mensaje]
    ADD CONSTRAINT [IX_Par_Mensaje_Codigo_Mensaje] UNIQUE NONCLUSTERED ([Codigo_Mensaje] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

