ALTER TABLE [dbo].[Ver_Etiqueta]
    ADD CONSTRAINT [IX_Ver_Etiqueta_Dic_Rotulo_Ver_Version] UNIQUE NONCLUSTERED ([Dic_Rotulo_Id] ASC, [Ver_Version_Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

