ALTER TABLE [dbo].[Apu_Indice_Equipo]
    ADD CONSTRAINT [PK_Apu_Indice_Equipo] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

