ALTER TABLE [dbo].[Apu_Oferta_Rubro]
    ADD CONSTRAINT [PK_Apu_Oferta_Rubro] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

