ALTER TABLE [dbo].[Par_Servidor_Det]
    ADD CONSTRAINT [PK_Par_Servidor_Det] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

