ALTER TABLE [dbo].[Seg_Rol_Menu]
    ADD CONSTRAINT [PK_Seg_Rol_Menu] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

