ALTER TABLE [dbo].[Ver_Etiqueta]
    ADD CONSTRAINT [PK_Ver_Etiqueta] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

