//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WKA_Rep.FIS {
    
    
    /// <summary>
    /// R_FIS_PLANILLA_REAJUSTE_REA class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class R_FIS_PLANILLA_REAJUSTE_REA {
        
        /// <summary>
        /// rpv_Fis_Planilla_Reajuste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.Reporting.WebForms.ReportViewer rpv_Fis_Planilla_Reajuste;
        
        /// <summary>
        /// odsFis_Planilla_Resumen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ObjectDataSource odsFis_Planilla_Resumen;
    }
}
