ALTER TABLE [dbo].[GDTRAMITE_FUNCIONARIO]
    ADD CONSTRAINT [FK_GDTRAMIT_REFERENCE_GDLISTRA] FOREIGN KEY ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDLISTRA] ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

