ALTER TABLE [dbo].[GDSECTAR]
    ADD CONSTRAINT [FK_GDSECTAR_REFERENCE_GDLISTAR2] FOREIGN KEY ([GD_TAREA_FINAL], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDLISTAR] ([GD_CODIGO_TAREA], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

