ALTER TABLE [dbo].[GDESTGES]
    ADD CONSTRAINT [FK_GDESTGES_RLSH_5_GDLISTRA] FOREIGN KEY ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDLISTRA] ([GD_CODIGO_TRAMITE], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE NO ACTION;

