ALTER TABLE [dbo].[GDTRAMITE_FUNCIONARIO]
    ADD CONSTRAINT [FK_GDTRAMIT_REFERENCE_GDFUNCIO] FOREIGN KEY ([GD_CODIGO_PERSONA]) REFERENCES [dbo].[GDFUNCIONARIOS] ([GD_CODIGO_PERSONA]) ON DELETE NO ACTION ON UPDATE CASCADE;

