ALTER TABLE [dbo].[GDFUNCIONARIO_AREA]
    ADD CONSTRAINT [FK_GDFUNCIO_REFERENCE_GDSUCURS] FOREIGN KEY ([GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION]) REFERENCES [dbo].[GDSUCURSAL] ([GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION]) ON DELETE NO ACTION ON UPDATE CASCADE;

