ALTER TABLE [dbo].[GDASIRES]
    ADD CONSTRAINT [FK_GDASIRES_GDINFTRA] FOREIGN KEY ([GD_NUMERO], [GD_PERIODO], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL], [GD_CODIGO_TRAMITE]) REFERENCES [dbo].[GDINFTRA] ([GD_NUMERO], [GD_PERIODO], [GD_CODIGO_INSTITUCION], [GD_CODIGO_SUCURSAL], [GD_CODIGO_TRAMITE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

