ALTER TABLE [dbo].[CONTRATISTAS]
    ADD CONSTRAINT [PK_AG_INFORCONTRATISTAS] PRIMARY KEY CLUSTERED ([ID_CONTRATISTA] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

