ALTER TABLE [dbo].[ADSCPASSW]
    ADD CONSTRAINT [PK_ADSCPASSW] PRIMARY KEY NONCLUSTERED ([ADPS_LOGIN] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

