ALTER TABLE [dbo].[GDSECTAR]
    ADD CONSTRAINT [PK_GDSECTAR] PRIMARY KEY CLUSTERED ([GD_TAREA_INICIAL] ASC, [GD_TAREA_FINAL] ASC, [GD_CODIGO_TRAMITE] ASC, [GD_CODIGO_INSTITUCION] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

