ALTER TABLE [dbo].[GDNUMINST]
    ADD CONSTRAINT [PK_GDNUMINST] PRIMARY KEY CLUSTERED ([GD_PERIODO_VIGENCIA] ASC, [GD_CODIGO_TRAMITE] ASC, [GD_CODIGO_INSTITUCION] ASC, [GD_CODIGO_SUCURSAL] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

