ALTER TABLE [dbo].[GDSEGTRA_HISTO]
    ADD CONSTRAINT [PK_GDSEGTRA_HISTO] PRIMARY KEY CLUSTERED ([GD_NUMERO] ASC, [GD_PERIODO] ASC, [GD_AREA_RESPONSABLE] ASC, [GD_NUMERO_SECUENCIAL] ASC, [GD_CODIGO_INSTITUCION] ASC, [GD_CODIGO_SUCURSAL] ASC, [GD_NUMERO_REESTRUCTURA] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

