ALTER TABLE [dbo].[GDSEGTRA]
    ADD CONSTRAINT [PK_GDSEGTRA] PRIMARY KEY CLUSTERED ([GD_CODIGO_INSTITUCION] ASC, [GD_CODIGO_SUCURSAL] ASC, [GD_PERIODO] ASC, [GD_CODIGO_TRAMITE] ASC, [GD_NUMERO] ASC, [GD_AREA_RESPONSABLE] ASC, [GD_NUMERO_REESTRUCTURA] ASC, [GD_NUMERO_SECUENCIAL] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

