ALTER TABLE [dbo].[GDINFTRA]
    ADD CONSTRAINT [PK_GDINFTRA] PRIMARY KEY CLUSTERED ([GD_NUMERO] ASC, [GD_PERIODO] ASC, [GD_CODIGO_INSTITUCION] ASC, [GD_CODIGO_SUCURSAL] ASC, [GD_CODIGO_TRAMITE] ASC) WITH (FILLFACTOR = 70, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

