ALTER TABLE [dbo].[SGOPCIONES]
    ADD CONSTRAINT [PK_SGOPCIONES] PRIMARY KEY CLUSTERED ([SG_CODIGO_OPCION] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

