CREATE STATISTICS [_dta_stat_562101043_17_3_5_4_2_1]
    ON [dbo].[GDSEGTRA]([GD_IMPRIMR_CE], [GD_PERIODO], [GD_NUMERO], [GD_CODIGO_TRAMITE], [GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION], [GD_AREA_RESPONSABLE], [GD_NUMERO_REESTRUCTURA], [GD_NUMERO_SECUENCIAL]);

