CREATE STATISTICS [_dta_stat_562101043_5_4_3_2_1_8_15_13_12_11_7_6]
    ON [dbo].[GDSEGTRA]([GD_NUMERO], [GD_CODIGO_TRAMITE], [GD_PERIODO], [GD_CODIGO_SUCURSAL], [GD_CODIGO_INSTITUCION], [GD_NUMERO_SECUENCIAL], [GD_FECHA_FINAL], [GD_FECHA_INICIO], [GD_CODIGO_TAREA], [GD_PERSONA_RESPONSABLE], [GD_NUMERO_REESTRUCTURA], [GD_AREA_RESPONSABLE]);

